### ISSUE TITLE
How to clear or delete the cookie?

### ISSUE THREAD

**Issue by amiyatulu** [flavors/django-graphql-jwt#102]
How can I clear the JWT cookie from the browser?

Can it be done by javascript, or backend (django-graphql-jwt) code is required?

**Comment by amiyatulu** [comment]
I have done it with react-cookies

```
import React, { Component } from 'react'
import cookie from 'react-cookies'



export default class SignOut extends Component {
    componentWillMount() {
        cookie.save('JWT',"")
        cookie.remove('JWT')
    }
    
    render() {
        return (
            <div>
              <p>You have successfully sign out.</p>  
            </div>
        )
    }
}
```

**Comment by amiyatulu** [comment]
Done with axios and django views

Django views
`from django.http import HttpResponse
def deleteJWT(request):
    # print(request.COOKIES)
    response = HttpResponse("Cookies Deleted")
    response.delete_cookie("JWT", path="/")
    return response `

And with axios:
`import React, { Component } from 'react'
import axios from 'axios'
import { apiUrl } from "../config.json"

export default class SignOut extends Component {
    componentDidMount() {
        axios.get(apiUrl + '/delcookie', {withCredentials: true}).then(res => {
            window.location="/"
        })
    }

    render() {
        return (
            <div>
              <p>You have successfully sign out.</p>  
            </div>
        )
    }
}
`

**Comment by Glyphack** [comment]
Why do you need a view that deletes cookie?

**Comment by amiyatulu** [comment]
> Why do you need a view that deletes cookie?

Than how to delete server-side cookies?  I am using jwt_cookie

`from django.urls import path

from graphene_django.views import GraphQLView
from graphql_jwt.decorators import jwt_cookie

urlpatterns = [
    path('graphql/', jwt_cookie(GraphQLView.as_view())),
]`

**Comment by JSeam2** [comment]
If you would like to logout you could delete the cookie on the client side. 

For example
```
import { Cookies } from 'react-cookie';

const cookie = new Cookies();

cookie.remove("COOKIE_NAME");
```

One approach is to set the cookie time to be really short, the default is 5 mins, and use a refreshToken to refresh the jwt_token. On the server side you can call revokeToken to revoke the refresh token for the jwt_token. I don't think that there is a function to invalidate a particular jwt_token.

I am guessing that a possible concern is that the jwt_token gets stolen and an attacker may use the remaining time to perform an attack or that you might want to handle multiple login sessions on different computers. Which would require you to invalidate a particular jwt_token. To my knowledge multiple session management has yet to be implemented and is something that can be looked into.

**Comment by Benjaminryejones** [comment]
+1 to this -- it would be nice if there was a built-in mutation that deletes a cookie rather than having to switch to using axios or another request library on the client-side if possible

**Comment by mcabrams** [comment]
FWIW, I have solved for now like so (note, I'm actually not revoking a token currently, but would love to learn how to do so):
```py
# urls.py
from django.contrib import admin
from django.urls import path

from graphene_django.views import GraphQLView
from graphql_jwt.decorators import jwt_cookie

class CustomGraphQLView(GraphQLView):
    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        response = self._delete_cookies_on_response_if_needed(request, response)
        return response

    def _delete_cookies_on_response_if_needed(self, request, response):
        data = self.parse_body(request)
        operation_name = self.get_graphql_params(request, data)[2]

        if operation_name and operation_name == 'Logout':
            response.delete_cookie('JWT')

        return response


urlpatterns = [
    path('admin/', admin.site.urls),
    path('graphql', jwt_cookie(CustomGraphQLView.as_view(graphiql=True))),
]
```

```py
# schema.py
....

class Logout(graphene.Mutation):
    """ The real action happens in our custom GraphQLView """
    # Just because we have to have a field, we put this; the meat occurs in the
    # GraphQLView where we remove the cookie
    noop = graphene.Field(graphene.Boolean)

    def mutate(self, info):
        # TODO: Consider revoking token here?
        pass

....
```

**Comment by yabesh12** [comment]
How to delete a Token from the server-side (mutation). when a user gives a logout the token will be destroyed from server-side by using mutation? is it possible? If so. please explain.
