### ISSUE TITLE
`WARNING: Added kwargs argument to JSONWebTokenMutation.resolve()` is unclear

### ISSUE THREAD

**Issue by relwell** [flavors/django-graphql-jwt#118]
Hi there! Thanks for this great package. It looks like the most recent update has caused an error in the `ObtainJSONWebToken` mutation. I've needed to revert to version 0.2.0 for now, but I'm hoping to understand what changes I need to make to continue using future versions of this package.

This seems backwards-incompatible. If the versioning is intended to follow semver, I have some concerns about the update being considered a patch instead of a minor or major update.

Could you please update the changelog with a reference to the commit where this changed, or instructions for how to update client code? Thanks!

**Comment by mongkok** [comment]
Hi @relwell ,
kwargs refers to the input/arguments of Graphene mutation.

I close the issue, if you have any questions please let me know.
