### ISSUE TITLE
token_issued signal

### ISSUE THREAD

**Issue by chiubaka** [flavors/django-graphql-jwt#121]
Hello! I noticed that there's been a recent (2 months ago) addition of a few signals to this project, including a `token_issued` signal. It also looks like there's been some experimentation with other signaling solutions, including providing an option to fire the `user_logged_in` signal upon successful JWT auth.

I'm interested in having some kind of post-login hook with my token-based auth, so wanted to ask: will either of these features make it into a minor release anytime soon?

**Comment by mongkok** [comment]
Hi @chiubaka ,
I created a new release including the signals:
`pip install django-graphql-jwt==0.2.2`
https://django-graphql-jwt.domake.io/en/latest/signals.html

I close the issue, if you have any questions please let me know.
