### ISSUE TITLE
Missing tag for v0.2.2

### ISSUE THREAD

**Issue by NyanKiyoshi** [flavors/django-graphql-jwt#126]
Hi,

I noticed the v0.2.2 release (4f8f3b90f53c6b3c4abb77a101587a756d7e26c3) was not tagged and the release note/changelogs don't tell the users about the middleware being no longer a DjangoMiddleware, thus potentially breaking their solution.

**Comment by mongkok** [comment]
Thanks @NyanKiyoshi ,
I've tagged version v0.2.2.
