### ISSUE TITLE
"AttributeError: '__proxy__' object has no attribute 'created'" after 0.2.2 update

### ISSUE THREAD

**Issue by douglasspeights** [flavors/django-graphql-jwt#129]
After updating to [0.2.2](https://pypi.org/project/django-graphql-jwt/0.2.2/), I'm getting the following Traceback:
```
Traceback (most recent call last):
  File "/.../python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/.../python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File ".../python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".../python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File ".../python3.7/site-packages/graphql_jwt/decorators.py", line 136, in wrapped_view
    expires = refresh_token.created +\
AttributeError: '__proxy__' object has no attribute 'created
```

I've added `JWT_REFRESH_EXPIRED_HANDLER` to settings, but still same error.

Also, after adding the `revoke_refresh_token` [recommendation](https://django-graphql-jwt.domake.io/en/latest/refresh_token.html?highlight=revoke_refresh_token#one-time-only-use-refresh-token), the token _is_ getting revoked, as subsequent calls (after getting above Traceback error) will fail for `Invalid refresh token` ...

Reverting back to 0.2.1 works as expected.

**Comment by martinsodabi** [comment]
Hi @douglasspeights, I am having the same issue after upgrading, had to downgrade as well, did you find a fix? Please let us know when you do, in the meantime, we just have to wait for @mongkok to respond.

**Comment by Dawidpol** [comment]
I have the same issue

**Comment by mongkok** [comment]
Thanks for reporting the bug @douglasspeights :)
I've created a new [PR 135](https://github.com/flavors/django-graphql-jwt/pull/135) to fix it.

**Comment by coltonbh** [comment]
Hi @mongkok. PR 135 didn't seem to fix the problem for me so I added another PR that addresses just the small bug that would make the jwt_cookie decorator function as expected [PR 140](https://github.com/flavors/django-graphql-jwt/pull/140)

**Comment by mongkok** [comment]
I'm sorry guys, I am just overloaded with work and I haven't been able to read it before.
The [PR 135](https://github.com/flavors/django-graphql-jwt/pull/135) is fixed and merged.

Thank you @coltonbh for the PR.

**Comment by Jasper-Koops** [comment]
No worries, thanks for the fix!
