### ISSUE TITLE
0.2.2 is a breaking change

### ISSUE THREAD

**Issue by relwell** [flavors/django-graphql-jwt#133]
When using pipenv, when installing a new dependency or removing an old one, there's a chance you'll install this version instead of 0.2.1. This will inexplicably break your existing middleware configurations without any sort of useful error message other than a generic `TypeError: __init__() takes 1 positional argument but 2 were given` coming out of `application = get_wsgi_application()` when `self.load_middleware()` is called.

This is a breaking change. It should definitely not be considered a patch update.

Please consider adding documentation around this, or introducing a new patch version that handles this error case more gracefully.

**Comment by mongkok** [comment]
Hey @relwell ,
Django Middleware is deprecated, add `JSONWebTokenMiddleware` middleware to your `GRAPHENE` settings:

```py
GRAPHENE = {
    'SCHEMA': 'mysite.myschema.schema',
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}
```
I close the issue, if you have any questions please let me know.
