### ISSUE TITLE
Permission for Mutation created from Serializer

### ISSUE THREAD

**Issue by ChangshengYan** [flavors/django-graphql-jwt#136]
Hi there,

This is a really awesome package and I really like it. But I have a question that I cannot find in the documentation. Some of my mutations are created from `SerializerMutation` and it has update & create mutation with it:

```
from graphene_django.rest_framework.mutation import SerializerMutation

class MySerializerMutation(SerializerMutation):
    class Meta:
        serializer_class = MySerializer
```

In this case, if I want to add permission and authentication to this mutation class I added the following code to the above class:

```
    @classmethod
    @staff_member_required
    def mutate_and_get_payload(cls, root, info, **input):
        kwargs = cls.get_serializer_kwargs(root, info, **input)
        serializer = cls._meta.serializer_class(**kwargs)

        if serializer.is_valid():
            return cls.perform_mutate(serializer, info)
        else:
            errors = ErrorType.from_errors(serializer.errors)

            return cls(errors=errors)
```

The only line I added to the source code copied from `SerializerMutation` is `@staff_member_required`, so I was wondering if there's any cleaner way to add this decorator? Do I need to repeatedly copy the classmethod `mutate_and_get_payload` and add `@staff_member_required` to it?

Thank you!
Changsheng

**Comment by mongkok** [comment]
Hey @ChangshengYan ,
Yes, its the only way, the decorator needs the `info` argument.
You can use `super()` to avoid code duplication.

I close the issue, if you have any questions please let me know.

**Comment by coler-j** [comment]
@mongkok can you re-open this with specific example? I just get the following error when trying to do a `super()` call:

```
mutate_and_get_payload() missing 1 required positional argument: 'info'
```

**Comment by PureTryOut** [comment]
I just experienced this issue, and indeed overwriting the `mutate_and_get_payload` method just to add the decorator works. A bit annoying but it's fine I suppose.

Current code to reduce code duplication:

```python
@classmethod
@superuser_required
def mutate_and_get_payload(cls, root, info, **input):
    return super().mutate_and_get_payload(root, info, **input)
```

I could however not find this in the documentation and it took me quite a while to find this issue with the solution. Can it be added to the docs somewhere?
