### ISSUE TITLE
Since DjangoMiddleware was removed, other middlewares report AnonymousUser for request.user

### ISSUE THREAD

**Issue by megri** [flavors/django-graphql-jwt#138]
My middleware list used to look like this:

```python
MIDDLEWARE = [
# … more middlewares
    'graphql_jwt.middleware.JSONWebTokenMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'my_custom_middleware1',
    'my_custom_middleware2',
# … more middlewares
]
```

Since the change to remove DjangoMiddleware, the server won't start if I leave in `graphql_jwt.middleware.JSONWebTokenMiddleware` and if I remove it my custom middlewares report that `request.user == AnonymousUser`.

I'm not sure how to upgrade to 0.2.2 with these changes. 0.2.1 seems to allow `graphql_jwt.middleware.JSONWebTokenMiddleware` in the "django middleware section".

**Comment by mongkok** [comment]
Hey @megri ,
I understand your problem, in my case, I decided to migrate all my Django middlewares to Graphene checking that they run once and not once per resolver.

The main reason for migrating to Graphene is to allow unrestricted access.
https://django-graphql-jwt.domake.io/en/latest/settings.html#permissions

e.g. tokenAuth, if you send an expired JWT and credentials (username/password):
- Django middleware returns an expiration error.
- Graphene middleware does not check the expired token and it returns a new token.

Graphene middleware knows the GraphQL queries, Django middleware doesn't.

I close the issue, if you have any questions please let me know.

**Comment by weilu** [comment]
@mongkok I ran into a similar problem while using this library with [django-auditlog](https://github.com/jazzband/django-auditlog/blob/master/auditlog/middleware.py). The auditlog library supports automatic change actor logging through a django middleware by installing pre-save signals in process_request and disconnect it in process_response. It gets the change actor from request.user which is always AnonymousUser with django-graphql-jwt. I wish there's a way to attach normal django middleware after graphene middleware, but I haven't found a way to do this, so I guess the proper way to make the two library work together is to roll my own graphene middleware, similar to the audtlog's middleware, right? Is there an equivalent to process_request and process_response in graphene middleware?

**Comment by weilu** [comment]
For the time being, I'm hacking it with this normal django middleware which checks request.user and calls authenticate if it's AnonymousUser. This way I can reuse the auditlog's middleware:

```python
from django.utils.functional import SimpleLazyObject
from django.contrib.auth import authenticate, get_user

def set_jwt_user(get_response):

    def get_jwt_user(request):
        user = get_user(request)
        if user.is_authenticated:
            return user
        jwt_user = authenticate(request)
        return jwt_user if jwt_user else user

    def middleware(request):
        request.user = SimpleLazyObject(
            lambda: get_jwt_user(request))
        return get_response(request)

    return middleware
```

Do you see any problem with this hack?
