### ISSUE TITLE
Decorator for checking group permissions

### ISSUE THREAD

**Issue by prabhupant** [flavors/django-graphql-jwt#144]
Feature Request.

Recently I was working on a project using django-graphql-jwt and I had to write my own decorator to check group permissions for users. I believe adding this decorator to the project will come in handy for other developers :smile:

**I am working on it**. Please assign this to me

**Comment by mongkok** [comment]
Hey @prabhupant, any updates?

**Comment by prabhupant** [comment]
@mongkok Sorry because of some things I wasn't able to work on this. Will get this PR up by this weekend for sure :+1:

**Comment by mongkok** [comment]
@prabhupant no rush at all :)

**Comment by mongkok** [comment]
You can use the [@permission-require](https://django-graphql-jwt.domake.io/en/latest/decorators.html#permission-required) decorator,
It checks user and group permissions using the [has_perms](https://docs.djangoproject.com/en/dev/ref/contrib/auth/#django.contrib.auth.models.User.has_perm) method on the User class.

I close the issue, if you have any questions, please let me know.
