### ISSUE TITLE
Get refreshToken in resolve custom method for long term running refresh tokens

### ISSUE THREAD

**Issue by ckristhoff** [flavors/django-graphql-jwt#145]
Hi everyone

I'm trying to get the token and refreshToken in my custom resolve method.
How can I get that?

**Comment by TitanFighter** [comment]
https://github.com/flavors/django-graphql-jwt/blob/master/graphql_jwt/shortcuts.py#L5

**Comment by mongkok** [comment]
As @TitanFighter says you can use the shortcuts functions.

I close the issue, if you have any questions please let me know.
