### ISSUE TITLE
Cannot change the error message on token auth

### ISSUE THREAD

**Issue by edmondlaja-quantix** [flavors/django-graphql-jwt#147]
Hello everyone,

I am trying to customise ObtainJSONWebToken so that when I call the tokenAuth and have invalid credentials, I would like to be able to have my own Exception that raises. 
I am trying using this [link](https://django-graphql-jwt.domake.io/en/latest/customizing.html).

Is it possible, if yes how?

Thanks

**Comment by begimai** [comment]
@edmondlaja-quantix  hi, did you find a way to resolve this issue?

**Comment by malobaidan** [comment]
Yes you can do it, In the link you provided you need to put the exception in the resolve method,If nothing is changing when you modify the resolve method, then you are doing something wrong ( I did that the first time), go to your root schema and in the mutation class change "token_auth = to.your.field"

I hope that helps

**Comment by mongkok** [comment]
Hey @edmondlaja-quantix ,
Try this:

```py
import graphql_jwt
from graphql_jwt.exceptions import JSONWebTokenError
from graphql_jwt.mixins import ResolveMixin


class ObtainJSONWebToken(graphql_jwt.JSONWebTokenMutation, ResolveMixin):

    @classmethod
    def mutate(cls, *args, **kwargs):
        try:
            return super().mutate_and_get_payload(*args, **kwargs)
        except JSONWebTokenError:
            raise Exception(':(')
```

I close the issue, if you have any questions please let me know.

**Comment by begimai** [comment]
@mongkok how can you set response status to 403? is it possible?
Because I have some public API, but django-graphql-jwt still validates token in header and FE can't catch this error without response status

**Comment by antiproblemist** [comment]
> Hey @edmondlaja-quantix ,
> Try this:
> 
> ```python
> import graphql_jwt
> from graphql_jwt.exceptions import JSONWebTokenError
> from graphql_jwt.mixins import ResolveMixin
> 
> 
> class ObtainJSONWebToken(graphql_jwt.JSONWebTokenMutation, ResolveMixin):
> 
>     @classmethod
>     def mutate(cls, *args, **kwargs):
>         try:
>             return super().mutate_and_get_payload(*args, **kwargs)
>         except JSONWebTokenError:
>             raise Exception(':(')
> ```
> 
> I close the issue, if you have any questions please let me know.

This gives an error `"'super' object has no attribute 'mutate_and_get_payload'",`

**Comment by umbauk** [comment]
> > Hey @edmondlaja-quantix ,
> > Try this:
> > ```python
> > import graphql_jwt
> > from graphql_jwt.exceptions import JSONWebTokenError
> > from graphql_jwt.mixins import ResolveMixin
> > 
> > 
> > class ObtainJSONWebToken(graphql_jwt.JSONWebTokenMutation, ResolveMixin):
> > 
> >     @classmethod
> >     def mutate(cls, *args, **kwargs):
> >         try:
> >             return super().mutate_and_get_payload(*args, **kwargs)
> >         except JSONWebTokenError:
> >             raise Exception(':(')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I close the issue, if you have any questions please let me know.
> 
> This gives an error `"'super' object has no attribute 'mutate_and_get_payload'",`

Replace `super().mutate_and_get_payload()` with `super().mutate()`

**Comment by Grunze1s** [comment]
I think we can use ErrorType provided by graphene_django to handle error response with new field errors.
```
import graphene
import graphql_jwt

from ..types import UserType
from graphene_django.types import ErrorType

from graphql_jwt.exceptions import JSONWebTokenError
from graphql_jwt.mixins import ResolveMixin

class CreateToken(graphql_jwt.JSONWebTokenMutation, ResolveMixin):
    user = graphene.Field(UserType)
    errors = graphene.List(ErrorType)

    @classmethod
    def mutate(cls, *args, **kwargs):
        try:
            return super().mutate(*args, **kwargs)
        except JSONWebTokenError as e:
            errors = ErrorType.from_errors({'username/password': [str(e)]})
            return cls(errors=errors)

    
    @classmethod
    def resolve(cls, root, info, **kwargs):
        return cls(user=info.context.user, errors=[])
```
