### ISSUE TITLE
How to override these environment variables

### ISSUE THREAD

**Issue by ImKcat** [flavors/django-graphql-jwt#15]
Thanks a lot at first, with this awesome library, it is easy to support JWT in project, so awesome!

But I got a little question with these environment variables, how to override them? What if I wanna change algorithm to HS512. I tried a few ways, but all failed and no effects.

**Comment by ImKcat** [comment]
@jonatasbaldin Thanks, but I tried, maybe somewhere I was doing wrong, like this in `settings.py`:
```python
JWT_ALGORITHM = 'HS512'
JWT_VERIFY_EXPIRATION = True
JWT_EXPIRATION_DELTA = timedelta(seconds=1) # Use 1 second just for testing
```

**Comment by mongkok** [comment]
Hi and thanks :)

configuration variables in the `settings.py` is not allowed, there is a related PR [JWT Settings](https://github.com/flavors/django-graphql-jwt/pulls), I'll merge it soon.

For now, you can configure the environment variables on the command line:

```sh
$ JWT_ALGORITHM=HS512
$ JWT_VERIFY_EXPIRATION=true
$ JWT_EXPIRATION_DELTA=seconds=1,hours=0
```

**Comment by ImKcat** [comment]
@mongkok OK, I got it!

 thanks for the work :)
