### ISSUE TITLE
Graphql-core 3.0.1

### ISSUE THREAD

**Issue by BfutureP** [flavors/django-graphql-jwt#156]
It doesn't support graphql-core 3.0.1 where graphene v3 required graphql-core 3.0.1.

**Comment by mongkok** [comment]
Hey @BfutureP ,
graphql-core >= 3 is not compatible with the latest **stable** version of graphene 2.1.8
https://pypi.org/project/graphene/#history

Once graphene upgrades to v3 I will update this package.

I close the issue, if you have any questions please let me know.
