### ISSUE TITLE
module 'jwt' has no attribute 'encode'

### ISSUE THREAD

**Issue by Onyebueke-Emmanuel** [flavors/django-graphql-jwt#161]
Recently i noticed this started with the **TokenAuth** Mutation, please what can be done

**Comment by mongkok** [comment]
Hi @Onyebueke-Emmanuel ,
this package requires `PyJWT >= 1.5.0` which includes the `encode` function.
Check the packages installed in your environment.
https://github.com/jpadilla/pyjwt/issues/374

I close the issue, if you have any questions please let me know.
