### ISSUE TITLE
Cannot read JWT token for refresh

### ISSUE THREAD

**Issue by raynear** [flavors/django-graphql-jwt#162]
Hello.

I want to refresh my JWT token.
but I cannot read JWT. because it's httponly cookie.
and I set jwt_cookie on urls.py from django.

path(r'graphql/', jwt_cookie(GraphQLView.as_view(graphiql=True, schema=schema)))

class Mutation(board.schema.MyMutation, graphene.ObjectType):
    token_auth = graphql_jwt.ObtainJSONWebToken.Field()
    verify_token = graphql_jwt.Verify.Field()
    refresh_token = graphql_jwt.Refresh.Field()

I cannot understand what is problem.

**Comment by JSeam2** [comment]
If the cookie is httpOnly you will not be able to read the JWT token programmatically on the browser via javascript. This should be handled by the browser.

**Comment by mongkok** [comment]
Hey @raynear ,
Try this PR: https://github.com/flavors/django-graphql-jwt/pull/165
Once you have the cookie stored you do not need to send any input field.

If you have any questions please let me know.
