### ISSUE TITLE
Getting more maintainers onboard

### ISSUE THREAD

**Issue by JSeam2** [flavors/django-graphql-jwt#163]
@mongkok will you be looking into getting more maintainers onboard? The library you've built is fantastic, but there may be quite a number of problems that people are facing and are looking to fix. As a result, I believe quite a number of us are resorting to using our own forks instead.

**Comment by mongkok** [comment]
Thank you @JSeam2 ,
Sadly I don't have much time available the short time I have left is enough for this project.
Maybe in the future...

I close the issue, if you have any questions please let me know.
