### ISSUE TITLE
Version 0.3.0 - Queries no updated

### ISSUE THREAD

**Issue by lovecrafteolin** [flavors/django-graphql-jwt#171]
Hi,
I have installed the version 0.3.0 and I don't get the new parameters like refreshExpiresIn
I sure that I do something wrong :(
![image](https://user-images.githubusercontent.com/55882356/74165026-cec87a00-4c24-11ea-8096-a4cdb365e9de.png)

System information
Operating system: Windows 10
Python version: 3.8.1

**Comment by TitanFighter** [comment]
because v0.3.0 does not include `refreshExpiresIn`. Wait for a new release or use git directly (instead of pypi). However I do not know if this feature ready to be used, in case of using git directly.

**Comment by lovecrafteolin** [comment]
thanks for you answer. I though that it was released because in the site shows available (latest).
I await when the new version will be released.

**Comment by lovecrafteolin** [comment]
thanks for you answer. I though that it was released because in the site shows available (latest).
I await when the new version will be released.

**Comment by mongkok** [comment]
Hi @lovecrafteolin ,
I just created a new release v0.3.1 including the `refreshExpiresIn` field.
I'm sorry for the delay in my response.
