### ISSUE TITLE
Change in graphql-core causes warnings to be raised when testing

### ISSUE THREAD

**Issue by jackscodemonkey** [flavors/django-graphql-jwt#177]
graphql-core 2.3.1 raises deprecation warnings when executing pytest queries with JSONWebTokenClient.

https://github.com/flavors/django-graphql-jwt/blob/49826780881ede1554c265fab1b3b41a4c038d05/graphql_jwt/testcases.py#L48

site-packages/graphql/backend/core.py:32: DeprecationWarning: The 'context' alias has been deprecated. Please use 'context_value' instead.
    return execute(schema, document_ast, *args, **kwargs)

site-packages/graphql/backend/core.py:32: DeprecationWarning: The 'variables' alias has been deprecated. Please use 'variable_values' instead.

**Comment by jackscodemonkey** [comment]
I can update this if you want to assign it to me.

**Comment by mongkok** [comment]
Thank you @jackscodemonkey ,
I've created a new PR #186 to fix the warnings.

I close the issue, if you have any questions please let me know.

**Comment by coler-j** [comment]
@mongkok I am on `0.3.1` and am currently getting this error when test (not a warning but a full error).
