### ISSUE TITLE
Could you please release a new version with a fixed cookies?

### ISSUE THREAD

**Issue by TitanFighter** [flavors/django-graphql-jwt#181]

**Comment by cutamar** [comment]
Can you elaborate on the problem? What is the specific issue?

**Comment by TitanFighter** [comment]
There are a lot of changes since the previous release, especially this one https://github.com/flavors/django-graphql-jwt/pull/165 , so it would be sweet to have a new version (for example v3.1) in npm.

**Comment by sbernier1** [comment]
yes please. Right now cookies aren't very convenient to use, there aren't any functions to refresh a cookie token or to remove it (logout).

**Comment by mongkok** [comment]
Hi @TitanFighter  :),
I just created a new release v0.3.1.
I'm sorry for the delay in my response.
