### ISSUE TITLE
customize the get_payload function 

### ISSUE THREAD

**Issue by aymaneMx** [flavors/django-graphql-jwt#184]
please, how can I customise the [get_payload](https://github.com/flavors/django-graphql-jwt/blob/master/graphql_jwt/utils.py#L84) function?

**Comment by aymaneMx** [comment]
here is the solution that I did for the moment:

I added this `JWT_DECODE_HANDLER` setting to `GRAPHQL_JWT`:
```
    GRAPHQL_JWT = {
        'JWT_DECODE_HANDLER': 'path_to_your_customized_jwt_decode',
    }
```
than here is my customized_jwt_decode function:
```
def customized_jwt_decode(token, context=None):
    try:
        payload = jwt_decode(token, context)
    except YourExceptionHere:
        # that ever you wanna do 
    return payload
```

**Comment by mongkok** [comment]
Hi @aymaneMx ,
Take a look the [documentation](https://django-graphql-jwt.domake.io/en/latest/settings.html), you can use the `JWT_PAYLOAD_HANDLER` setting:

```py
from graphql_jwt.utils import jwt_payload


def my_jwt_payload(user, context):
    payload = jwt_payload(user, context)
    payload['foo'] = '...'
    return payload


GRAPHQL_JWT = {
    'JWT_PAYLOAD_HANDLER': my_jwt_payload,
}
```

I close the issue, if you have any questions please let me know.
