### ISSUE TITLE
adding @login_required to resolvers prevents people logged in from accessing

### ISSUE THREAD

**Issue by Quickinline** [flavors/django-graphql-jwt#189]
I setup a "me" query to test authentication. the query doesn't work when adding the token to the header, I'm using Insomnia and I don't know how to fix it.
although with insomnia I'm able to verify and acquire token with the correct credentials

![JWT_token_sent](https://user-images.githubusercontent.com/39879172/78807607-3a785a80-79bc-11ea-8111-26972625e735.png)
![verifyToken](https://user-images.githubusercontent.com/39879172/78807629-3fd5a500-79bc-11ea-988f-9c1f96f2ac41.png)

**Comment by ulgens** [comment]
@Quickinline What was the issue and how it is resolved?

**Comment by Quickinline** [comment]
the issue was that adding my authentication token to the header didn't grant me access to @login_required queries.
turns out I had a duplicate GRAPHENE dictionnary in my settings.py
the second one didn't have the middleware in it's parameters so the middleware never executed at the first place
