### ISSUE TITLE
Auto-refresh token expiration date

### ISSUE THREAD

**Issue by aarzuagat** [flavors/django-graphql-jwt#190]
I have this problem: If I refresh my token every 5 minutes, I want to automatically update payload.exp if user did something in that time (before 5 minutes). I see unnecessary to token_auth to get a new token every 5 minute cause "Signature has expired". I want to do that automatically. How could I do?

**Comment by austincollinpena** [comment]
Did you find a solution to this?

**Comment by aarzuagat** [comment]
> Did you find a solution to this?

I did. Thanks!

**Comment by austincollinpena** [comment]
What was your solution?

**Comment by aarzuagat** [comment]
The trouble was in the objective of those functions:
1. refresh_token was built to a short age (no more)
2. token_auth was built to a long age.
For example: If you're gonna share a file with friends, you should use refresh token, cause at n hours, minutes or something else... That token dies. Auth is revoked and file can't be downloaded anymore.
Token auth is to give access in a long time.
Did I explain me?

**Comment by austincollinpena** [comment]
But the refresh token shouldn't be used for access control, right?

**Comment by aarzuagat** [comment]
You can. But remember its timelife is short (and it must be short, in other case you should use token auth).
I repeat: token refresh is an access token to a shorter time.
