### ISSUE TITLE
graphql_jwt.DeleteRefreshTokenCookie.Field() is wrong in document 

### ISSUE THREAD

**Issue by PyDevX** [flavors/django-graphql-jwt#192]
Link : https://django-graphql-jwt.domake.io/en/latest/authentication.html#delete-cookies
Section : Delete Cookies 
Wrong  :   # Long running refresh tokens
    delete_refresh_token_cookie = \
        graphql_jwt.refresh_token.DeleteRefreshTokenCookie.Field()

Right :  # Long running refresh tokens
    delete_refresh_token_cookie = \
        graphql_jwt.DeleteRefreshTokenCookie.Field()

**Comment by mongkok** [comment]
Thank you @PyDevX :)
