### ISSUE TITLE
Error field not following general convention

### ISSUE THREAD

**Issue by cutamar** [flavors/django-graphql-jwt#193]
At the moment `django-graphql-jwt` returns errors in:
```
{data: {}, errors: []}
```
but this error array is meant only for errors made by developers. User-made errors should be returned in the `data` attribute, like it's done in graphene serializer mutations. The way it is now it's not following the spec of e.g. the relay client. I can't get to the errors array because a real error gets raised in the client.

**Comment by mongkok** [comment]
Hi @cutamar,
There is no specification that defines an error format within the data array.
https://spec.graphql.org/June2018/#sec-Errors

If you have any questions regarding the error format please open an issue in the Graphene project.
