### ISSUE TITLE
Refresh tokens are being generated even when not requested.

### ISSUE THREAD

**Issue by benrussell80** [flavors/django-graphql-jwt#199]
# Problem
Similar to this closed issue, #81, whenever I call `refreshToken` a new long-running refresh token is created even if I don't include `refreshToken` in the return query. In that issue, a solution was said to have been made where a new one would not be created unless it was asked for in the response, but I am still seeing more long-running refresh tokens being made.

# My setup
- Python 3.8.2
- Ubuntu 18.04
- Firefox
- Output from `pip freeze`:
```
aniso8601==7.0.0
asgiref==3.2.7
boto3==1.13.6
botocore==1.16.6
dj-database-url==0.5.0
Django==3.0.6
django-autoslug==1.9.7
django-cors-headers==3.2.1
django-filter==2.2.0
django-graphql-jwt==0.3.1
django-heroku==0.3.1
django-storages==1.9.1
docutils==0.15.2
graphene==2.1.8
graphene-django==2.9.1
graphql-core==2.3.1
graphql-relay==2.0.1
gunicorn==20.0.4
jmespath==0.9.5
Pillow==7.1.2
promise==2.3
psycopg2-binary==2.8.5
PyJWT==1.7.1
python-dateutil==2.8.1
python-dotenv==0.13.0
pytz==2020.1
Rx==1.6.1
s3transfer==0.3.3
singledispatch==3.4.0.3
six==1.14.0
sqlparse==0.3.1
urllib3==1.25.9
whitenoise==5.0.1
```
- Pertinent parts of `urls.py`
```python
from django.urls import path
from graphene_django.views import GraphQLView
from graphql_jwt.decorators import jwt_cookie


urlpatterns = [
    ...,
    path('graphql/', jwt_cookie(GraphQLView.as_view(graphiql=True)), name='graphql'),
    ...,
]
```
- Mutations
```python
import graphene
import graphql_jwt


class Mutation(graphene.ObjectType):
    token_auth = graphql_jwt.relay.ObtainJSONWebToken.Field()
    verify_token = graphql_jwt.relay.Verify.Field()
    refresh_token = graphql_jwt.relay.Refresh.Field()
    delete_token_cookie = graphql_jwt.relay.DeleteJSONWebTokenCookie.Field()
    
    revoke_token = graphql_jwt.relay.Revoke.Field()
    delete_refresh_token_cookie = graphql_jwt.relay.DeleteRefreshTokenCookie.Field()
```

# Request Being Made
I make this request in the graphiql console with `{"refreshToken": "..."}` in request variables and I get the value by copyting from the JWT-refresh-token cookie.

```graphql
mutation RefreshToken($refreshToken: String!) {
  refreshToken(input: {refreshToken: $refreshToken}) {
    token
    payload
  }
}
```

# Result
After sending that request, the JWT-refresh-token cookie changes to a different value, and there is a new one in the database (after looking at `RefreshToken.objects.count()` before and after).

Could this due to the `jwt_cookie` decorator creating a new one? Is there a way to refresh the token (access token) without creating a new refresh token?

**Comment by mongkok** [comment]
Hi @benrussell80,
Cookie-based authentication generates a refresh token even if it is not specified in the GraphQL query.
According to your comments, I recommend you to take a look `JWT_REUSE_REFRESH_TOKENS` and `JWT_HIDE_TOKEN_FIELDS` settings:
https://django-graphql-jwt.domake.io/en/latest/settings.html

This might be a good setting for a cookie-based authentication:
```py
GRAPHQL_JWT = {
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LONG_RUNNING_REFRESH_TOKEN': True,
    'JWT_REUSE_REFRESH_TOKENS': True,
    'JWT_HIDE_TOKEN_FIELDS': True,
}
```
 
I close the issue, if you have any questions please let me know.
