### ISSUE TITLE
How to generate - access token vs refresh token

### ISSUE THREAD

**Issue by vintage** [flavors/django-graphql-jwt#2]
Hey,

I have a problem in understanding on how to generate properly access token and refresh token. According to the docs there is a concept of both due to `JWT_REFRESH_EXPIRATION_DELTA` and `JWT_EXPIRATION_DELTA` configuration variables, but in the source files I've seen only single method for generating a token which is https://github.com/flavors/django-graphql-jwt/blob/master/graphql_jwt/shortcuts.py#L4

The flow which I would like to follow is:
1. User sign-up/sign-in to the app
2. User receives two tokens: `access_token` (valid for 5 minutes) and `refresh_token` (valid for 7 days)
3. The `access_token` is used to communicate frontend app with the backend API
4. The `refresh_token` is used to regenerate the `access_token` in intervals, so it would be valid during using the app in longer session

Is it correct approach to such scenario?

```
access_token = get_token(user)
refresh_token = get_token(user, exp=datetime.utcnow() + settings.JWT_REFRESH_EXPIRATION_DELTA)
```

**Comment by mongkok** [comment]
Hey @vintage ,
you do not need a second token to refresh, there is no field in the JWT payload that specifies the type of token (refresh/access_token).

Use the refresh and update for a new one:

```graphql
mutation  {
  refreshToken(token: "-token-") {
    token
    payload
  }
}
```

the settings:
```sh
JWT_VERIFY_EXPIRATION=true
JWT_REFRESH_EXPIRATION_DELTA=days=7
JWT_EXPIRATION_DELTA=minutes=5
```

It means that you need to refresh every 5 mins and even you keep on refreshing token every 5 mins, you will still be logout in 7 days after the first token has been issued.

**Comment by mongkok** [comment]
@vintage https://github.com/flavors/django-graphql-jwt/wiki/Token-expiration

**Comment by vintage** [comment]
Thanks a lot @mongkok, it seems I've misunderstood the concept a bit :) Works like a charm!

**Comment by tunarob** [comment]
1 question to this great explanation. How to keep the user logged in “forever” then? Well, forever as long as he keeps rehreshing within allowed JWT_EXPIRATION_DELTA time span (as I understand I’d refresh triggered after the time of 5 minutes in this case, token gets invalidated?)

I could set JWT_REFRESH_EXPIRATION_DELTA to be like 30 days but it’s still not forever.

**Comment by globophobe** [comment]
IJWT_VERIFY_EXPIRATION is false by default, which is the same as forever.

**Comment by mongkok** [comment]
that's the way :-)

**Comment by googol7** [comment]
What happens if I don’t call `refreshToken` after `JWT_EXPIRATION_DELTA=minutes=5` but within `JWT_REFRESH_EXPIRATION_DELTA=days=7`? Will `verifyToken(t)` return `false` if `JWT_VERIFY_EXPIRATION=true` but refreshToken will return a new valid token? Or does `JWT_VERIFY_EXPIRATION` need to be turned off in order to refresh an expired token?

**Comment by TitanFighter** [comment]
@googol7 According to my tests, 
with the next settings:

```
JWT_VERIFY_EXPIRATION=true
JWT_REFRESH_EXPIRATION_DELTA=days=7
JWT_EXPIRATION_DELTA=minutes=5
```

you should call `refreshToken` < 5 mins. In this case you will get refreshed token.

If you call `refreshToken` > 5 mins OR `verifyToken` with a token which has not been created / refreshed within 5 mins, you will get:

```
{
    "errors": [
        {
            "message": "Signature has expired",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "refreshToken"  # or "verifyToken"
            ]
        }
    ],
    "data": {
        "refreshToken": null  # or "verifyToken": null
    }
}
```
