### ISSUE TITLE
Get rid of configuration with environment variables

### ISSUE THREAD

**Issue by zenwalker** [flavors/django-graphql-jwt#20]
I think that using environment variables to configure the application could be harmful. I have at least four reasons why I think it should be removed: 

1. As far as I know, Django has the only one official way to configure our applications—the `settings.py` file. I think it is beyond the responsibility of the third-party application to define alternative ways how this application can be configured. 

2. It will cause some hard-to-debug bugs or even vulnerabilities, as we’re talking about authentication, if some of the JWT_* variables have been defined somehow without the developers’ knowledge or because the developers don't expect that authentication may be configured somehow but `settings.py` because (see item 1) it is unnatural behavior for third-party apps.

3. It also brings an unnecessary dependency in my project which I probably don’t want to have. Or maybe even the conflicts if my project requires a different version of django-environ. 

4. It is just unnecessary. If I wanted to configure JWT with env variables, I’d do it myself in the `settings.py`.

**Comment by mongkok** [comment]
Hi @zenwalker,
I agree with each of the points you mention.

In my opinion environment variables are the way to separate config from code, but I agree that it should be the developer who makes that decision.

https://12factor.net/config

In terms of security, I don't think that environment variables are a problem as long as they are not public.

Thanks for this interesting point of view, if you want to submit a PR it will be welcome :).

**Comment by zenwalker** [comment]
@mongkok Sure, I’ll do this soon. Thank you :)

**Comment by mongkok** [comment]
done (https://github.com/flavors/django-graphql-jwt/pull/31),
thanks for the suggestion!
