### ISSUE TITLE
Remove Did you mean...

### ISSUE THREAD

**Issue by ckristhoff** [flavors/django-graphql-jwt#207]
Hi
When you post an wrong writted query, graphql/graphene makes suggestions to you. By example, sending "i", it suggest "ID".
```graphql
query{
  users{
        i
  }
}
```
```
{
  "errors": [
    {
      "message": "Cannot query field \"i\" on type \"User\". Did you mean \"id\"?",
      "locations": [
        {
          "line": 5,
          "column": 9
        }
      ]
    }
  ]
}
```
How can I remove suggestions on query errors?

**Comment by mongkok** [comment]
Hi @ckristhoff ,
This package does not handle syntax errors, see https://github.com/graphql-python/graphql-core.
If you want to modify the error message you can override the `format_error` method by creating a class inherited from `graphene_django.views.GraphQLView` class.

I close the issue, if you have any questions please let me know.
