### ISSUE TITLE
Use Email Authentication Method Instead of Username

### ISSUE THREAD

**Issue by atticuslin** [flavors/django-graphql-jwt#209]
Hello,

I am trying to modify my login page such that I can use a user's email and password to login instead of the default including the username. I have tried overriding the JSONWebTokenMutation flow but have had no success. Any suggestions?

`class ObtainJSONWebToken(graphql_jwt.JSONWebTokenMutation):
	user = graphene.Field(UserType)
	print(user)

	class Arguments:
		email = graphene.String()
		password = graphene.String()

	@classmethod
	def Field(cls, *args, **kwargs):
		cls._meta.arguments.update({
			get_user_model().EMAIL_FIELD: graphene.String(required=True),
			'password': graphene.String(required=True),
		})
		print(cls._meta.arguments)
		return super().Field(*args, **kwargs)

	@classmethod
	# @token_auth
	def mutate(cls, root, info, **kwargs):
		user = authenticate(email=kwargs['email'], password = kwargs['password'])
		if user is None:
			raise Exception('Credentials are incorrect')
		token = get_token(user)
		info.context.set_jwt_cookie=token
		return cls(user=user, token=token)

	@classmethod
	def resolve(cls, root, info, **kwargs):
		return cls(user=info.context.user)
`

**Comment by TitanFighter** [comment]
Here is my old [simplified] code which worked (currently my project in deep refactoring so can not double check the code).

```
import graphene

from django.contrib.auth import get_user_model

from graphene_django import DjangoObjectType
from graphql_jwt import JSONWebTokenMutation

User = get_user_model()


class UserType(DjangoObjectType):
    class Meta:
        model = User

class UserEmailAuth(JSONWebTokenMutation):
    """
    Example of query from Front End.

    mutation {
      userEmailAuth(email: "test@domain.com", password: "Password") {
        token,
        status,
        user {
          id,
          username
        }
      }
    }
    """

    status = graphene.String()
    user = graphene.Field(UserType)

    @classmethod
    def resolve(cls, root, info, **kwargs):
        user = info.context.user

        if user.is_active:
            status = 'ok'
        else:
            status = 'Your account has not been activated, because your email has not been confirmed.')

        return cls(status=status, user=user)
```

**Comment by austincollinpena** [comment]
Extending AbstractBaseUser and replacing the username field with an email field is what did it for me. No need to extend any token auth or other shenanigans.

**Comment by mongkok** [comment]
As @austincollinpena says you can create a custom user model, `USERNAME_FIELD = 'email'`: https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#specifying-a-custom-user-model

I close the issue, if you have any questions please let me know.
