### ISSUE TITLE
User last_login is not updated on token auth

### ISSUE THREAD

**Issue by Shannanigans** [flavors/django-graphql-jwt#211]
I might have missed something but it appears to me that the user field 'last_login' is not updated by jwt authentication.

**Comment by mongkok** [comment]
Hi @Shannanigans,
Some developers may not want to update the `last_login` field when the token is issued.

You can send the `user_logged_in` using `token_issued` signal:

```py
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver

from graphql_jwt.signals import token_issued


@receiver(token_issued)
def update_last_login(sender, request, user, **kwargs):
    user_logged_in.send(sender, user=user, request=request)
```

I close the issue, please let me know if you have any questions.

**Comment by Shannanigans** [comment]
Hi @mongkok thanks for the feedback and snippet :smile:
