### ISSUE TITLE
graphql_jwt.relay.ObtainJSONWebToken returns token when wrong credentials are submitted and Authorization header is set

### ISSUE THREAD

**Issue by vladcalin** [flavors/django-graphql-jwt#22]
I ran into a case when I had two users, `A` and `B`, and was sending a valid token of `A` when trying to obtain a new token for `B`. The mutation doesn't return any error, but instead returns a new token for `A`.

I dig a little in the code and I found out it was because of using `authenticate` here: https://github.com/flavors/django-graphql-jwt/blob/master/graphql_jwt/decorators.py#L69 , as the middleware will authenticate the user using the token instead of validating against the credentials.

So I ended up in a situation where, no matter what I was sending in the mutation input args, I was getting a valid token for  another user.

I believe that mutation should validate the credentials instead of using all middlewares to authenticate the user.

A possible fix that pops in my mind right now would be calling `authenticate` only with username and password.

What do you think about this? 

Thank you.

**Comment by mongkok** [comment]
Thanks @vladcalin,

As you say, `authenticate()` function checks credentials against each authentication backend specified in the `AUTHENTICATION_BACKENDS` setting.

`graphql_jwt.backends.JSONWebTokenBackend` reads the *Authorization* header and returns the authenticated user.

how to fix it?

a. Avoid the default request parameter so `JSONWebTokenBackend` could not obtain the token (but some backends could require the request object).

b. Remove the *Authorization* header before `authenticate()`, `info.context.META.pop(jwt_settings.JWT_AUTH_HEADER, None)`

c. Create a custom [authenticate()](https://docs.djangoproject.com/en/2.0/_modules/django/contrib/auth/#authenticate) function and exclude `JSONWebTokenBackend` from the `AUTHENTICATION_BACKENDS` setting (I don't think it's the right approach).

**Comment by mongkok** [comment]
@vladcalin fixed on master.
