### ISSUE TITLE
[QUESTION] How to log in in both the React SPA and regular Django admin site?

### ISSUE THREAD

**Issue by pdonadeo** [flavors/django-graphql-jwt#221]
Sorry if I drop here a question but I did not found any other discussion group.

This is my use case: I have a private app consisting of a complex dashboard (React + Apollo Client) and a Django backend, and of course I'm using django-graphql-jwt. I've successfully set up authentication via cookie + CSRF token, it works like a charm.

Now I'm forced to go live before the dashboard is complete (guess what... :disappointed:) so we decided to give the customer access the Django admin site, at least in the development period of the dashboard.

The main entry point of the app is the dashboard login so I'd like the user could to log in both the React SPA (it's already working, as said) **and** the Django admin site: I have added a link to `/admin` in the dashboard menu but in this moment the user is requested to log in again, which seems acceptable to me... but the customer has a different idea :unamused: 

Any advice to save me?

**Comment by pdonadeo** [comment]
Just solved. Sorry for the noise.

**Comment by makridenko** [comment]
Hello, what is solution? Thnx!

**Comment by pdonadeo** [comment]
> Hello, what is solution? Thnx!

Essentially chaining (from the React form) a regular login into Django and, if it succeeded, sending the login mutation, like this:

```javascript
function SignIn(props) {
  const { loggedIn, setLoggedIn, setAuthTokens } = useAuth();

  const [isError, setIsError] = useState(false);
  const [gql_login] = useMutation(LOGIN);

  const tryLogin = (e) => {
    e.preventDefault();

    const userName = window.document.getElementById("email").value;
    const password = window.document.getElementById("password").value;

    const formData = new FormData();

    fetch("/en/admin/login/?next=/en/admin/", {
      method: "GET",
      credentials: "same-origin",
      headers: {
        Accept:
          "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      },
    })
    .then((response) => {
    formData.append("username", userName);
    formData.append("password", password);
    formData.append("next", "/en/admin/");
    fetch("/en/admin/login/", {
      method: "POST",
      body: formData,
      credentials: "same-origin",
      headers: {
        "X-CSRFToken": Cookies.get("csrftoken"),
      },
    })
      .then((response) => response.text())
      .then((result) => {
        gql_login({
          variables: {
            username: userName,
            password: password,
          },
        }).then(
          (data) => {
            setAuthTokens(data.data.tokenAuth.token);
            setLoggedIn(true);
          },
          (err) => {
            setIsError(true);
          }
        );
      })
      .catch((error) => {
        console.error("Error:", error);
      })
      .catch((error) => {
        console.error("Error loading Django admin login form");
      });
  });
  };

  if (loggedIn) {
    return <Redirect to="/" />;
  }

  return (
    <JSX LOGIN FORM HERE />
  );
}

export default SignIn;
```

The first `fetch` to Django also gives you che CSRF token.

**Comment by makridenko** [comment]
Thank you for your answer! What if user does not have access to django-admin?

**Comment by makridenko** [comment]
And what about this situation: user has loged in from another user in admin-page. Client has old JWT?

**Comment by pdonadeo** [comment]
> And what about this situation: user has loged in from another user in admin-page. Client has old JWT?

Yes the client has the old JWT. In my use case this is not a problem at all because:

1. the entry point of the application is still the React SPA
2. the access to `/admin` is temporary and will be removed when the app will be completed

In any case it's easy to extend the Django SessionMiddleware to delete the JWT.
