### ISSUE TITLE
Being able to issue a JWT outside graphql.

### ISSUE THREAD

**Issue by emilpriver** [flavors/django-graphql-jwt#228]
Hi, I am currently working on building a social sign in system with this package (if possible).
Is there a way to generate a JWT and return it to the user via graphql?
Like a function that takes a user id and so on

Dear,
Emil

**Comment by debdutgoswami** [comment]
@emilpriver Yes, this can done and it is in fact the most basic functionality of the package. Refer to the official documentation to see how you can set this up.

**Comment by emilpriver** [comment]
I am not talking about using tokenAuth mutation. I am talking about being able to use a function in the code to generate a JWT when using a custom sign in. Ex via Twitter

**Comment by debdutgoswami** [comment]
@emilpriver No, that is not possible as of now. You can use Firebase login for that. It generates JWT for you and you can likewise use it to authenticate with your backend

**Comment by emilpriver** [comment]
ok, got ya. Any plans in the future to integrate it?
