### ISSUE TITLE
Token cannot be created ('str' has no attribute 'decode')

### ISSUE THREAD

**Issue by bsiebens** [flavors/django-graphql-jwt#241]
I've recently started to incorporate GraphQL into one of my existing projects. Installed django-graphql-jwt according to the documentation but whenever I run the below, I get the following error:

`mutation {
  tokenAuth(
    username: "dummy",
    password: "dummydummy"
  ) {
    token
  }
}`

`{
  "errors": [
    {
      "message": "'str' object has no attribute 'decode'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "tokenAuth"
      ]
    }
  ],
  "data": {
    "tokenAuth": null
  }
}`

I've searched almost everywhere but I cannot track down what the issue and as far as I can see it should work?

Relevant pieces of code:
Settings.py
```GRAPHENE = {
    "SCHEMA": "blackbook.schema.schema",
    "MIDDLEWARE": [
        "graphql_jwt.middleware.JSONWebTokenMiddleware",
        "graphene_django.debug.DjangoDebugMiddleware",
    ],
}
```

Blackbook.schema
```import graphene
import graphql_jwt

from .api import user


class Query(user.Query, graphene.ObjectType):
    pass


class Mutation(graphene.ObjectType):
    token_auth = graphql_jwt.ObtainJSONWebToken.Field()
    verify_token = graphql_jwt.Verify.Field()
    refresh_token = graphql_jwt.Refresh.Field()


schema = graphene.Schema(query=Query, mutation=Mutation)```
```

**Comment by bsiebens** [comment]
Further investigation learned that this is a change in pyjwt, where as from version 2.0.0 the token returned will not be a sequences of bytes but a string. Solved for now by pinning the version of pyjwt to <2.

**Comment by kubami** [comment]
This error is raised precisely in `utils.py`:

```
def jwt_encode(payload, context=None):
    return jwt.encode(
        payload,
        jwt_settings.JWT_PRIVATE_KEY or jwt_settings.JWT_SECRET_KEY,
        jwt_settings.JWT_ALGORITHM,
    ).decode('utf-8')
```

on the `decode(...)`

I fixed it by pinning the `pyjwt` as well to < 2.

**Comment by gtg7784** [comment]
I had this error too, I was fixed this error with changing utils.py

jwt.encode function return 'str', so I changed utils.py jwt_encode function below

```py
def jwt_encode(payload, context=None):
    return jwt.encode(
        payload,
        jwt_settings.JWT_PRIVATE_KEY or jwt_settings.JWT_SECRET_KEY,
        jwt_settings.JWT_ALGORITHM,
    )
```

**Comment by gtg7784** [comment]
Another option to fix this issue, install PyJWT==1.7.0

**Comment by Rosenmatt1** [comment]
How do I access the utils.py folder?  It's not showing up on my Visual Studio Code IDE.

**Comment by gtg7784** [comment]
> How do I access the utils.py file? It's not showing up on my Visual Studio Code IDE.

You can access the utils.py at 
```
site-packages/graphql_jwt/utils.py
```

**Comment by Rosenmatt1** [comment]
@gtg7784 How do I access site-packages?  I'm not seeing in in my GUI, IDE, or terminal...

**Comment by TitanFighter** [comment]
@Rosenmatt1 no one knows how python is installed on your pc. There are differences between OS + there is a chance you use venv. Check installation folder of your python (or vent), something like `python3/lib/python3.8/site-packages/graphql_jwt/utils.py`.

P.S. Your question is not related to the topic.

**Comment by gtg7784** [comment]
> @gtg7784 How do I access site-packages? I'm not seeing in in my GUI, IDE, or terminal...

You can find the path of site-packages directory to execute below in terminal or cmd

```sh
python -c 'import site; print(site.getsitepackages())'
```

**Comment by cristiangrojas** [comment]
This really needs to get fixed.

I've an scenario where this becomes a real pain...

I'm using [stream-python](https://github.com/GetStream/stream-python) which requires pyjwt==2.0.1 and fails with pyjwt==1.7.0, so obviously downgrading isn't a solution.

**Comment by gtg7784** [comment]
> This really needs to get fixed.
> 
> I've an scenario where this becomes a real pain...
> 
> I'm using [stream-python](https://github.com/GetStream/stream-python) which requires pyjwt==2.0.1 and fails with pyjwt==1.7.0, so obviously downgrading isn't a solution.

if you want to use pyjwt over 1.7.0 version, you should fix utils.py
```site-packages/graphql_jwt/utils.py```

https://github.com/flavors/django-graphql-jwt/issues/241#issuecomment-758477509

this comment will be helpful

**Comment by coler-j** [comment]
@kimutaiRop so this issue should be re-opened?
