### ISSUE TITLE
Unhandled Rejection (Error): GraphQL error: String cannot represent value: 

### ISSUE THREAD

**Issue by digitalw** [flavors/django-graphql-jwt#259]
Hi,
I hope this is the right repo for this, as it is linked here from https://pypi.org/project/django-graphql-jwt-reload/

Using:
django-graphql-jwt-reload 1.3.6 
and the mutation:
`
mutation TokenAuth($username: String!, $password: String!) {
  tokenAuth(username: $username, password: $password) {
    token,
    payload,
  }
}
`

I get the error 

`
Unhandled Rejection (Error): GraphQL error: String cannot represent value: b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRyYWluZXIiLCJleHAiOjE2MTcxOTA0ODZ9.owSp5Bn-T8Hhh1vI6wr4DTdWLm42-4ZKLy3V30rIp9w'
`

when I remove `token` from the query it seems to work, however then I do not have the token. 
Any ideas on how to fix this?

thanks

**Comment by digitalw** [comment]
Ok, looks like the issue comes from unstable versions required by graphene-django-extras: 0.5.1 . reverted back and am now removing this dependency. hopefully this will solve my issue

**Comment by veryacademy** [comment]
This works 👍

aniso8601==7.0.0
appdirs==1.4.4
asgiref==3.3.1
black==20.8b1
click==7.1.2
Django==3.1.7
django-cors-headers==3.7.0
django-graphql-jwt==0.3.1
django-js-asset==1.2.2
django-mptt==0.12.0
djangorestframework==3.12.2
graphene==2.1.8
graphene-django==2.15.0
graphql-core==2.3.2
graphql-relay==2.0.1
isort==5.7.0
mypy-extensions==0.4.3
pathspec==0.8.1
Pillow==8.1.2
promise==2.3
PyJWT==1.7.1
pytz==2021.1
regex==2020.11.13
Rx==1.6.1
singledispatch==3.6.1
six==1.15.0
sqlparse==0.4.1
text-unidecode==1.3
toml==0.10.2
typed-ast==1.4.2
typing-extensions==3.7.4.3

**Comment by HosseyNJF** [comment]
I'm still facing this bug. Any solutions?

These are the dependencies:
```
aniso8601==7.0.0
asgiref==3.2.3
astroid==2.3.3
autopep8==1.5
Django==2.2.10
django-cors-headers==3.2.1
django-environ==0.4.5
django-filter==2.4.0
django-graphql-jwt==0.3.2
django-safedelete==0.5.4
djangorestframework==3.11.0
djangorestframework-jwt==1.11.0
graphene==3.0b7
graphene-django==3.0.0b7
graphql-core==3.1.4
graphql-relay==3.1.0
gunicorn==20.0.4
isort==4.3.21
jsonfield==2.0.2
lazy-object-proxy==1.4.3
mccabe==0.6.1
Pillow==8.1.0
promise==2.3
psycopg2-binary==2.8.6
pycodestyle==2.5.0
PyJWT==1.7.1
pylint==2.4.4
pytz==2019.3
Rx==1.6.1
singledispatch==3.4.0.3
six==1.14.0
sqlparse==0.3.0
text-unidecode==1.3
typed-ast==1.4.1
whitenoise==5.2.0
wrapt==1.11.2
```

**Comment by realce2** [comment]
I recreated a python3.7 venv, reinstalled all my packages, and it fixed itself.

I'd suggest you have a broken python3 environment somehow, mine was very messy after an upgrade from 3.6 to 3.7
