### ISSUE TITLE
HTTP header authentication: why "Authorization: JWT {token}" instead of "Authorization: Bearer {token}"?

### ISSUE THREAD

**Issue by andsav** [flavors/django-graphql-jwt#269]
First of all, thanks for this library, it is very useful! 

While integrating this with my website, I noticed I need to use `Authorization: JWT {token}` instead of the [standard](https://swagger.io/docs/specification/authentication/bearer-authentication/) `Authorization: Bearer {token}`.

![image](https://user-images.githubusercontent.com/5506087/118385324-bf23a800-b5c2-11eb-91fa-71163eaf10b9.png)

Was there a reason for this choice? I think it creates some confusion.

**Comment by dtrodger** [comment]
You can set the [JWT_AUTH_HEADER_PREFIX](https://github.com/flavors/django-graphql-jwt/blob/master/graphql_jwt/settings.py#L26) in Django settings file to to Bearer.

```
GRAPHQL_JWT = {
    "JWT_AUTH_HEADER_PREFIX": "Bearer"
}
```

**Comment by alvintangz** [comment]
It's honesty up to any developer's interpretation to set the type in the `Authorization` header. Developers using this will most of the time not create an OAuth 2.0 server in which the `Bearer` type is standard. As @dtrodger has mentioned, you can set your own auth header prefix.

**Comment by andsav** [comment]
Gotcha, it's not a big deal since it's configurable. I'll use that solution. Thanks!

**Comment by alvintangz** [comment]
@andsav you should close the issue

**Comment by philihp** [comment]
Agree that this is confusing. Would you be open to support both `Bearer` and `JWT` by default, or to switch to `Bearer` on the next major version? I'm happy to throw up a PR if this would be considered.
