### ISSUE TITLE
Unable to complete installation of requirements because django-graphql-jwt depends on graphql-core<3 and >=2.1 which is not compatible with other packages

### ISSUE THREAD

**Issue by ryarasi** [flavors/django-graphql-jwt#270]
##Problem

I am working on a Django project and I'm unable to complete the installation of requirements (requirements.txt file below) because the dependency spec on django-graphql-jwt specifies a version range of graphql-core that is incompatible with most other packages that I'm using in my project. And most of these packages are not even that far-fetched.

Requirements.txt file:-

```
aniso8601==8.1.1
asgiref==3.3.4
autopep8==1.5.7
Django==3.2.3
django-cors-headers==3.7.0
django-filter==2.4.0
django-graphql-auth==0.3.16
django-graphql-jwt==0.3.2
djangorestframework==3.12.4
graphene==3.0b7
graphene-django==3.0.0b7
graphene-django-extras==0.5.1
graphql-core==3.1.5
graphql-relay==3.1.0
promise==2.3
psycopg2==2.8.6
pycodestyle==2.7.0
PyJWT==1.7.1
python-dateutil==2.8.1
pytz==2021.1
Rx==1.6.1
singledispatch==3.6.1
six==1.16.0
sqlparse==0.4.1
text-unidecode==1.3
toml==0.10.2

```

docker-compose build fails with this
```
ERROR: Cannot install -r requirements.txt (line 8) and graphql-core==3.1.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested graphql-core==3.1.5
    django-graphql-jwt 0.3.0 depends on graphql-core<3 and >=2.1
```

The latest version 0.3.2 results in this:-
```
ERROR: Cannot install -r requirements.txt (line 7) and django-graphql-jwt==0.3.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested django-graphql-jwt==0.3.2
    django-graphql-auth 0.3.16 depends on django-graphql-jwt==0.3.0
```
I tried changing the version of graphql-core but it led to a lot of other packages not being compatible.

What's the way around this?

**Comment by CrazyCatCZ** [comment]
Yeah having the same problem

**Comment by mongkok** [comment]
Hey @ryarasi , I have created a new release [0.3.3](https://github.com/flavors/django-graphql-jwt/releases/tag/0.3.3) to support Graphene V2 and any graphql-core version, see [setup.py](https://github.com/flavors/django-graphql-jwt/blob/master/setup.py#L39-L42).
I close the issue, if you have any questions please let me know.
