### ISSUE TITLE
Unable to Get Refresh Token From `tokenAuth` Mutation

### ISSUE THREAD

**Issue by JayOneTheSk8** [flavors/django-graphql-jwt#271]
`{
  "errors": [
    {
      "message": "Cannot query field \"payload\" on type \"ObtainJSONWebToken\".",
      "locations": [
        {
          "line": 14,
          "column": 5
        }
      ]
    }
  ]
}`

I'm receiving this when using the `tokenAuth` mutation. I can't access the values they listed here:

`mutation TokenAuth($username: String!, $password: String!) {
  tokenAuth(username: $username, password: $password) {
    token
    payload
    refreshToken
    refreshExpiresIn
  }
}`

**Comment by Theophylline** [comment]
Were you able to solve this? I have the same issue after following the doc instructions on long running refresh tokens

**Comment by W1773ND** [comment]
> Were you able to solve this? I have the same issue after following the doc instructions on long running refresh tokens. The payload field doesn't exist.

Just add
```
GRAPHQL_JWT = {
...
     JWT_LONG_RUNNING_REFRESH_TOKEN = True
}
```

in your settings.py

**Comment by JayOneTheSk8** [comment]
> Were you able to solve this? I have the same issue after following the doc instructions on long running refresh tokens. The payload field doesn't exist.

I had to update the graphql_jwt package to the latest working version

**Comment by Lucasmiguelmac** [comment]
I have this problem. None of the solutions fixed it for me unfortunately.

**Comment by sam-254** [comment]
```
INSTALLED_APPS = [
    .......
    'graphql_jwt.refresh_token.apps.RefreshTokenConfig',
    .....
    ]
```
    add this in your Projects INSTALLED_APPS and migrate
