### ISSUE TITLE
Does 0.3.2 not support graphene 2?

### ISSUE THREAD

**Issue by abs** [flavors/django-graphql-jwt#277]
'graphene-django>=3.0.0b1' makes it impossible to install against graphene < 3 -- is that intentional?

https://github.com/flavors/django-graphql-jwt/blob/4a22654ebc1e697ecef2027d11d1539a33b17598/setup.py#L40

**Comment by mongkok** [comment]
Thanks for heads up @abs, that was a bad decision, I have created a new release [0.3.3](https://github.com/flavors/django-graphql-jwt/releases/tag/0.3.3) to support Graphene V2.
I close the issue, if you have any questions please let me know.
