### ISSUE TITLE
Automated mutation testing with input variables

### ISSUE THREAD

**Issue by ayding11** [flavors/django-graphql-jwt#278]
Hello, 

I am trying to test a mutation with an input variable. I have tried adding the input to variables, but get an error:  

'Variable "$input" of required type [...] was not provided.'

Could someone please help with this issue? Many thanks!
 
Here is the code:

```python
class GQLTestCase(JSONWebTokenTestCase):

    def setUp(self):
        self.user = get_user_model().objects.create(username='testuser')
        self.client.authenticate(self.user)
    
    def test_mutation(self):
    
    	mutation = '''
    		mutation updateModel($input: UpdateModelInputType!) {
                updateModel(input: $input) {
                    model {
                        id
                        name
                    }
                }
            }
    	'''
        
        model_id = 1
        
        variables = {
            'username': self.user.username,
            'inuput':{'id': model_id },
        }
        
        response = self.client.execute( update_mutation, variables )
 	self.assertIsNone(response.errors)
        
```

Others seem to be having the same issue:
[https://stackoverflow.com/questions/59509280/django-graphql-endpoint-testing-unable-to-use-variables-dictionary](url)

**Comment by mongkok** [comment]
hey @ayding11 , please try this:
```py
variables = {
    'input': {
        'username': self.user.username,
        'inuput':{'id': model_id },
    },
}
```

**Comment by ayding11** [comment]
Hi @mongkok , I tried the solution you provided, but it ran into other errors. Interestingly, when trying the original code, it worked! I must have had another issue in my schema definition. Sorry for the bother and thanks for your help.
