### ISSUE TITLE
Configurable field instead of USERNAME_FIELD.

### ISSUE THREAD

**Issue by svengt** [flavors/django-graphql-jwt#28]
I'm having some difficulties with the username field as an unique identifier. I'm using email as username field in my project and superusers have the ability to change this value. When this happens the users token gets invalidated and will be logged out once he tries to refresh his token.

Other reason why it could by a good idea to pick another field is that this could lead to some security issues which are discussed in [this](https://github.com/GetBlimp/django-rest-framework-jwt/issues/244) issue.

**Comment by mongkok** [comment]
Hi @svengt ,
there's a related PR https://github.com/flavors/django-graphql-jwt/pull/17, I could include the `JWT_PAYLOAD_GET_USERNAME_HANDLER ` setting soon.

**Comment by mongkok** [comment]
@svengt added JWT_PAYLOAD_GET_USERNAME_HANDLER setting variable.

**Comment by svengt** [comment]
@mongkok Thx for the update!
