### ISSUE TITLE
register with custom AdminSite

### ISSUE THREAD

**Issue by saeedhmt** [flavors/django-graphql-jwt#281]
Hi. I have a custom `AdminSite` and my apps are registered with that.

![admin](https://user-images.githubusercontent.com/58300378/127104504-d7caa1d3-0a50-4364-be40-bc4ba62fa179.png)

now I wanna register `RefreshToken` of the package with that admin. How can I do that?

**Comment by mongkok** [comment]
Hey @saeedhmt, have a look at [Django docs](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#customizing-the-adminsite-class):


```py
from graphql_jwt.refresh_token.models import RefreshToken

class CustomAdminSite(AdminSite):
    ...

admin_site = CustomAdminSite()
admin_site.register(RefreshToken)
```
