### ISSUE TITLE
Manually obtain JSON Web Token

### ISSUE THREAD

**Issue by fahadakhan96** [flavors/django-graphql-jwt#29]
Is it possible to manually obtain a JSON Web Token on the server-side? I'm trying to return the token in the mutation that creates a user.

I tried:
```python
jwt_token = graphql_jwt.ObtainJSONWebToken(username=username, password=password)
```
but this did not work.

**Comment by kawasakikou** [comment]
username and password are an invalid keyword argument.
please try

      jwt_token = graphql_jwt.ObtainJSONWebToken()

**Comment by mongkok** [comment]
Hi @fahadakhan96 ,

you could use the `get_token` function:

```py
from graphql_jwt.shortcuts import get_token

get_token(user)
```
