### ISSUE TITLE
Is this project active ??

### ISSUE THREAD

**Issue by jackton1** [flavors/django-graphql-jwt#290]

**Comment by aaonhub** [comment]
no

**Comment by IIsijola** [comment]
alternatives to this project?

**Comment by Kinzowa** [comment]
> alternatives to this project?

Maybe this ? https://django-rest-framework-simplejwt.readthedocs.io/en/latest/getting_started.html

**Comment by webjunkie** [comment]
> alternatives to this project?

Seems like this could be something:

https://github.com/KundaPanda/strawberry-django-jwt
