### ISSUE TITLE
How to delete a Token from the server-side (mutation). when a user gives a logout the token will be destroyed from server-side by using mutation? is it possible? If so. please explain.

### ISSUE THREAD

**Issue by yabesh12** [flavors/django-graphql-jwt#301]

**Comment by TitanFighter** [comment]
JWT is stateless authentication approach, ie server-side does not store any info about token, so nothing to remove. Either you need another authentication appoach or you need to add a DB and respecive code to store info about tokens (in order to have something to delete).

**Comment by yabesh12** [comment]
Okay. I got a better approach without  creating the DB for jwt. https://github.com/flavors/django-graphql-jwt/issues/11#issuecomment-616806837
