### ISSUE TITLE
fails if root object types not named Query and Mutation

### ISSUE THREAD

**Issue by odigity** [flavors/django-graphql-jwt#304]
I believe [this code](https://github.com/flavors/django-graphql-jwt/blob/main/graphql_jwt/middleware.py#L16) is assuming the operation type ('query' or 'mutation') can be title-ized to produce the name of the root query and mutation types, but the GraphQL spec doesn't require that:

    def allow_any(info, **kwargs):
        operation_name = get_operation_name(info.operation.operation).title()
        field = info.schema.get_type(operation_name).fields.get(info.field_name)

This fails if you have something like this:

    class Foo(ObjectType):
        hello = String(default_value='Hi!')

    schema = Schema(query=Foo)

**Comment by nrbnlulu** [comment]
I believe this repo is dead bruh...
you should probably move on to strawberry

**Comment by odigity** [comment]
Yeah, I've noticed the rot and cobwebs on both this package and graphene.  At the moment, I'm tasked with understanding and improving our existing system.  However, I definitely intend to review the alternatives (Strawberry, Tartiflette, Ariadne) in the near future in the hopes of finding one I like more than graphene, and adopting during an API re-write.

**Comment by nrbnlulu** [comment]
Good luck!
