### ISSUE TITLE
Authentication/Authorization for default resolvers

### ISSUE THREAD

**Issue by amreshprasad** [flavors/django-graphql-jwt#36]
Hi,
I read the description on how to use @login_required and other decorators with resolvers. However, if one is not using explicit resolvers (instead using default ones), how can one enforce similar access controls?

In my case, I am using graphene with the Django User model. I have the following:

```
class UserNode(DjangoObjectType):
    class Meta:
        model = User
        filter_fields = ['first_name', 'last_name', 'id', 'email']
        interfaces = (Node, )

class Query(object):
    userNode = relay.Node.Field(UserNode)
    all_users = DjangoConnectionField(UserNode)
```

If I explicitly define a 'resolve_all_users' method and use the @login_required decorator on it, it works fine. But this (and other objects) in my schema are relying on default resolvers. How can I protect them without having to define resolvers explicitly?

I admit to being a novice in the use of graphene/graphql......and any help pointing me in the right direction is much appreciated.

**Comment by AlonsoEnrique** [comment]
@amreshprasad ask in https://stackoverflow.com/. I'm also interested.

**Comment by AlonsoEnrique** [comment]
@amreshprasad done: https://stackoverflow.com/questions/52523234/authentication-authorization-for-default-resolvers

**Comment by amreshprasad** [comment]
@AlonsoEnrique Thanks.

**Comment by amreshprasad** [comment]
@mongkok The fact that you added the enhancement label - does it mean that there is no way to achieve this currently other than by explicitly defining the resolvers?

**Comment by Speedy1991** [comment]
One way to bundle your resolvers is to protect the Type by the parent:

```
class Container:
  def __init__(self, **kwargs):
    for k, v in kwargs.items():
      setattr(self, k, v)

class BType(graphene.ObjectType)
  a = graphene.String()
  b = graphene.String()

class AType(graphene.ObjectType):
  c = graphene.Field(BType)

  @login_required
  def resolve_c(self, info, **kwargs):
    return Container(a="a", b="b")

class Query(graphene.ObjectType):
  protected = graphene.Field(AType)
  unprotected = graphene.Field(BType)

  def resolve_protected(self, info, **kwargs):
    return Container()

  def resolve_unprotected(self, info, **kwargs):
    return Container(a="a", b="b") 
```

The idea is, to generate only through parents access to child resolvers

This will raise if the user is not authenticated: `{protected { c {a b} }}`
But this will work: `{unprotected { a b } }`

**Comment by ytmimi** [comment]
@amreshprasad @AlonsoEnrique, Heres one way to ensure all fields for a given ObjectType are restricted to authenticated users.

If you take a look at where DjangoObjectType is defined in the source [code](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/types.py) you see that DjangoObjectType inherits from ObjectType. One of the Meta attributes for ObjectType is default_resolver. 

Just so you know, here's how Graphene defines its default resolver:
```Python
def attr_resolver(attname, default_value, root, info, **args):
     return getattr(root, attname, default_value)
```

Reading the [decorator docs](https://django-graphql-jwt.domake.io/en/latest/decorators.html) explains that login_required just checks that the current user is logged in (or authenticated). 

Also, important to note: **info.context is our Django request object**. 

Putting that all together we can define a custom resolver and apply it to our DjangoObjectType.
```Python
from graphql_jwt.exceptions import PermissionDenied

def auth_resolver(attname, default_value, root, info, **args):
    if info.context.user.is_authenticated:
        return getattr(root, attname, default_value)
    raise PermissionDenied()

class UserNode(DjangoObjectType):
    class Meta:
        model = User
        filter_fields = ['first_name', 'last_name', 'id', 'email']
        interfaces = (Node, )
        default_resolver = auth_resolver
```
As long as you set up django-graphql-jwt correctly, passing in a valid token will set the user object in info.context, and this method should work.

**Comment by mongkok** [comment]
I think this is a good proposal:
https://github.com/graphql-python/graphene/pull/846

I close the issue.
