### ISSUE TITLE
How to implement Remember Me function?

### ISSUE THREAD

**Issue by TitanFighter** [flavors/django-graphql-jwt#37]
Hi @mongkok .

Could you please help me a bit to understand how to implement Remember Me function?

As a reference I took your [answer](https://github.com/flavors/django-graphql-jwt/issues/2#issuecomment-357709219) and [my tests](https://github.com/flavors/django-graphql-jwt/issues/2#issuecomment-424451507).

So, as mentioned in your answer, the next settings ...:

```
JWT_VERIFY_EXPIRATION=true
JWT_REFRESH_EXPIRATION_DELTA=days=7
JWT_EXPIRATION_DELTA=minutes=5
```

> ... means that you need to refresh every 5 mins and even you keep on refreshing token every 5 mins, you will still be logout in 7 days after the first token has been issued.

It's clear, but taking into account the aforesaid, I do not understand, how to achieve the next behavior:
1. User clicks 'Remember me' (for example this function works 7 days, ie `JWT_REFRESH_EXPIRATION_DELTA=days=7`) and front-end stores received token in cookies or localStorage.
2. User does not leave site for 30 mins. During this time token is refreshed (and stored in cookies or localStorage) 6+ times (ie `JWT_EXPIRATION_DELTA=minutes=5`).
3. User closes site / browser.
4. Next day user comes back, but with the settings mentioned above and with my tests the last refreshed token is not valid any more -> "Signature has expired", so, front-end should automatically logout user and ask user to log in again (despite the fact that the user ticked 'Remember me' and this function should keep user logged in for the next 6 days).

Initially I thought the refreshing, lets say every 5 mins, is used for security reason and I thought that all refreshed tokens actually lives until 7 days since the first token created and I wanted to use this for Remember Me function, but after my tests I see that token lives just 5 mins.

If set `JWT_ALLOW_REFRESH` to False, ie do not refresh token and let the first created token lives for the next 7 days, as I understand, this is insecure way.

Probably I do not see something. Could you help please?

**Comment by mongkok** [comment]
Hi @TitanFighter :)

I think the easiest way is to send `HTTP` header and configure a `JWT_PAYLOAD_HANDLER` in your settings.

```py
from datetime import timedelta

from graphql_jwt.utils import jwt_payload


def custom_jwt_payload(user, context):
    payload = jwt_payload(user)

    if context.META.get('HTTP_REMEMBER_ME', False):
    	payload['exp'] += timedelta(days=7)

    return payload


GRAPHQL_JWT = {
    'JWT_PAYLOAD_HANDLER': custom_jwt_payload,
}
```
So you do not need to refresh a token for 7 days + `JWT_EXPIRATION_DELTA`.

**Comment by TitanFighter** [comment]
I thought about something like that...

I want to clarify: Am I right that the token refresh is used for the security purpose? If so, then in the case of `So you do not need to refresh a token for 7 days` we lose some level of security.

Maybe, could it be a good idea to add into `django-graphql-jwt` Remember Me function with the next logic:
- refresh token, lets say every 5 mins, when REMEMBER_ME user online (the same behavior as now);
- allow `django-graphql-jwt` to refresh token, when user comes back next day and send:
  - `HTTP_REMEMBER_ME`;
  - a token with expired `exp`, but ok-ish `orig_iat + JWT_REFRESH_EXPIRATION_DELTA`;
- when `orig_iat + JWT_REFRESH_EXPIRATION_DELTA` is expired, send `Signature has expired`

What you think?

**Comment by mongkok** [comment]
Hi!
I think you should not refresh the token if the user selected `remember me` and would not use an HTTP header to bypass the refresh for security reasons.

For the moment, I have no plans to include it in this package.

**Comment by TitanFighter** [comment]
Thanks!

**Comment by TitanFighter** [comment]
@mongkok I copy-pasted your code and I have a problem:

> graphql.error.located_error.GraphQLLocatedError: 'NoneType' object has no attribute 'META'

so, the `context` from your example is None. Any ideas?
