### ISSUE TITLE
Automated testing example

### ISSUE THREAD

**Issue by eclar** [flavors/django-graphql-jwt#38]
Hello,

Would it be possible to have an example on how to tests the queries and mutations using this library ? At the moment, I haven't managed to test properly those because the `@login_required` is enabled and graphene cannot execute the requested queries on the schema. If you have an example of middleware to be used for the tests or any solutions I would be very interested.

Thanks in advance,

**Comment by TitanFighter** [comment]
Basic tests can be done by using [Insomnia](https://insomnia.rest/).

In the header select POST and provide address (something like `http://localhost:8000/api/graphql/v1`)

Here is the example of Relay mutation:
```
mutation {
  verifyToken(input:{token: "-YOUR-TOKEN-"}) {
    payload
  }
}
```
Is it what you are looking for?

**Comment by mongkok** [comment]
Hi @eclar ,

you can try [this PR (39)](https://github.com/flavors/django-graphql-jwt/pull/39) to write your tests.

```py
from django.contrib.auth import get_user_model

from graphql_jwt.testcases import GraphQLJWTTestCase


class UsersTests(GraphQLJWTTestCase):

    def setUp(self):
        self.user = get_user_model().objects.create(username='test')
        self.client.authenticate(self.user)

    def test_users(self):
        query = '''
        {
          users {
            id
          }
        }'''
        self.client.execute(query, variables={})
```
the `variables` argument is optional.

**Comment by mongkok** [comment]
Merged and created a new release.
```sh
pip install django-graphql-jwt>=0.1.13
```

I have renamed the class to `JSONWebTokenTestCase`.
https://github.com/flavors/django-graphql-jwt#writing-tests

Happy testing :)

**Comment by eclar** [comment]
Thanks a lot @mongkok !

**Comment by guilhermewebdev** [comment]
Hello @mongkok , I'm tring implemens this, but how i can use asserts? because the self.client.execute function returns a object, and I need to compare it whith a dict, how in graphene tests

**Comment by coler-j** [comment]
@mongkok it returns a `graphql.execution.base.ExecutionResult` how can we get the `json` data from that?

**Comment by ayding11** [comment]
Hello, 

I am trying to test a mutation with an input variable. I have tried adding the input to variables, but get an error:  

'Variable "$input" of required type [...] was not provided.'

Could someone please help with this issue? @mongkok is this possible? Many thanks!
 
Here is the code:

```python
class GQLTestCase(JSONWebTokenTestCase):

    def setUp(self):
        self.user = get_user_model().objects.create(username='testuser')
        self.client.authenticate(self.user)
    
    def test_mutation(self):
    
    	mutation = '''
    		mutation updateModel($input: UpdateModelInputType!) {
                updateModel(input: $input) {
                    model {
                        id
                        name
                    }
                }
            }
    	'''
        
        model_id = 1
        
        variables = {
            'username': self.user.username,
            'inuput':{'id': model_id },
        }
        
        response = self.client.execute( update_mutation, variables )
 	self.assertIsNone(response.errors)
        
```

Someone else seems to have had the same issue:
[https://stackoverflow.com/questions/59509280/django-graphql-endpoint-testing-unable-to-use-variables-dictionary](url)

**Comment by danihodovic** [comment]
Is there a wrapper for pytest?
