### ISSUE TITLE
Current user - always anonymus

### ISSUE THREAD

**Issue by maltitco** [flavors/django-graphql-jwt#4]
I am looking for a solution to confirm the id of the logged in user and add it to the field in the forms.

```python
class CreateLink(graphene.Mutation):
    id = graphene.Int()
    url = graphene.String()
    description = graphene.String()
    posted_by = graphene.Field(UserType)

    class Arguments:
        url = graphene.String()
        description = graphene.String()

    def mutate(self, info, url, description):
        user = info.context.user
        if user.is_anonymous:
            raise GraphQLError('Authentication credentials were not provided')

        link = Link(
            url=url,
            description=description,
            posted_by=user,
        )
        link.save()

        return CreateLink(
            id=link.id,
            url=link.url,
            description=link.description,
            posted_by=link.posted_by,
        )
```

But I still have information that the user is anonymous

**Comment by mongkok** [comment]
Hi @maltitco,

If the user is authenticated, this exception should not be thrown:

```python
if user.is_anonymous:
    raise GraphQLError('Authentication credentials were not provided')
```


If you have this error it could be for several reasons.

- The middleware/backend are not configured

```python
MIDDLEWARE = [
    ...
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ...
]

AUTHENTICATION_BACKENDS = [
    'graphql_jwt.backends.JSONWebTokenBackend',
    'django.contrib.auth.backends.ModelBackend',
]
```

- You are not sending the authentication header
`Authorization: JWT -token-`


This is a howtographql fork that includes this library and authenticates correctly.
https://github.com/mongkok/graphql-python/tree/json-web-token

**Comment by maltitco** [comment]
@mongkok thanks for the fast response.
The middleware/backend are configured correct - checked twice with your fork of howtographql.

You were right that it was missing: Authorization: JWT -token-
Thanks for your help.

**Comment by mongkok** [comment]
I'm glad it helped :)
