### ISSUE TITLE
Graphene backend with django-graphql-jwt honoring expired token

### ISSUE THREAD

**Issue by amreshprasad** [flavors/django-graphql-jwt#40]
Using version 0.1.13 of django-graphql-jwt.

I am finding that the package is honoring expired tokens. I've used the Insomnia desktop client to verify. On the Django-side I am using a Graphene backend. To test, I used a simple graphql query, with a resolver that is protected using the @login_required decorator. The token I used in the header had been fetched 5 hours ago and should have expired 5 minutes later (I verified that by using jwt.io debugger to decode the token and determine the expiration time, then used the Epoch Converter at epochconverter.com to verify that the token did indeed expire 5 hours ago).

To make sure that the decorator is functional, I disabled the token in the header. And as expected the graphql query failed with:

```
{
	"errors": [
		{
			"message": "You do not have permission to perform this action",
			"locations": [
				{
					"column": 3,
					"line": 2
				}
			]
		}
	],
	"data": {
		"allUsers": null
	}
}

```
Also on the backend the following trace was logged, indicating that it was django-graphql-jwt package that was doing the authentication:

```
  File "/home/xxx/code/dev/local/lib/python2.7/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/home/xxx/code/dev/local/lib/python2.7/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
  File "/home/xxx/code/dev/local/lib/python2.7/site-packages/graphene_django/debug/middleware.py", line 56, in resolve
    promise = next(root, info, **args)
  File "/home/xxx/code/dev/local/lib/python2.7/site-packages/graphql/execution/middleware.py", line 57, in make_it_promise
    return Promise.resolve(next(*a, **b))
  File "/home/xxx/code/dev/local/lib/python2.7/site-packages/graphene_django/fields.py", line 122, in connection_resolver
    iterable = resolver(root, info, **args)
  File "/home/xxx/code/dev/local/lib/python2.7/site-packages/graphql_jwt/decorators.py", line 27, in wrapper
    return func(info.context, *args, **kwargs)
  File "/home/xxx/code/dev/local/lib/python2.7/site-packages/graphql_jwt/decorators.py", line 39, in wrapper
    raise exceptions.PermissionDenied()
PermissionDenied: You do not have permission to perform this action
```

Have  I got something misconfigured or is this a regression? I am using default django-graphql-jwt settings. I found this to also occur on 0.1.12.

**Comment by amreshprasad** [comment]
Another interesting thing of note: When I do get the 'permission denied' message above without the auth token, I get a http status code of 200 (I would have expected a 401). Is this expected behavior?

**Comment by mongkok** [comment]
Hi @amreshprasad ,
Have you set the flag `JWT_VERIFY_EXPIRATION` in your settings?

```py
GRAPHQL_JWT = {
    'JWT_VERIFY_EXPIRATION': True
}
```

**Comment by amreshprasad** [comment]
Thanks Mongkok. That's what it was. I should have read the documentation more carefully, duh!!

Am now facing another issue, wherein if the token expires and the user provides username/password again and the code hits the TokenAuth graphql query with the credentials, I get an unauthorized error based on the expired token in the header. Should the module not ignore the expired token for the TokenAuth query?

Thanks once again. Much appreciated.

**Comment by TitanFighter** [comment]
> wherein if the token expires ... I get an unauthorized error based on the expired token in the header

... you need to clean the header once token is expired (or do not let token to be expired by refreshing it every x mins and replacing it in the header)

So by cleaning the header, the next
> the user provides username/password again and the code hits the TokenAuth graphql query with the credentials

... does not happen and user gets fresh token.

**Comment by amreshprasad** [comment]
Yes, TitanFighter. I figured that out too. Just thought that the backend could have handled that scenario.

Got it working now. Thanks to you and Mongkok. Closing....

**Comment by mongkok** [comment]
yes @amreshprasad, 
I agree, but it is the middleware that checks if the token has expired, not the mutation.
I can not find an easy way to avoid the expiration error for `TokenAuth`.
