### ISSUE TITLE
Is there any reason to send token twice (in the header and in the query) in case of using verifyToken and refreshToken?

### ISSUE THREAD

**Issue by TitanFighter** [flavors/django-graphql-jwt#41]
I understand cases when we need to verify/refresh token which differs from the header, but is there any real reason to send the same token in the header and in the query in order to verify/refresh it?

I think graphql-jwt should check whether token in query is provided and if no, should take it from the header and verify/refresh it (via `get_authorization_header`).

**Comment by mongkok** [comment]
Hi @TitanFighter,
The authentication header is not used to verify and refresh tokens, credentials are not required.

**Comment by TitanFighter** [comment]
Hi @mongkok 

> The authentication header is not used to verify and refresh tokens, credentials are not required.
Yes, I know, but what I am thinking about is the next case: when a user is already authenticated, we already use authentication header and additionally from time to time we anyway refresh it, so in this case we can refresh token based on the header. It was just a proposition :)

Regarding token verification... I implemented it in the wrong way... Now I see that at first it should be verified and after this it should be add to the header.

**Comment by mongkok** [comment]
Is a good proposal @TitanFighter, but for this package I would prefer a required token within GraphQL schema.

```py
from django.utils.translation import ugettext as _

import graphene
from graphene.types.generic import GenericScalar
from graphql_jwt.exceptions import JSONWebTokenError
from graphql_jwt.utils import get_authorization_header, get_payload


class Verify(graphene.Mutation):
    payload = GenericScalar()

    class Arguments:
        token = graphene.String()

    @classmethod
    def mutate(cls, root, info, token=None, **kwargs):
        if token is None:
            token = get_authorization_header(info.context)

        if token is None:
            JSONWebTokenError(_('Token is required'))

        return cls(payload=get_payload(token, info.context))
```
