### ISSUE TITLE
Login with email and username

### ISSUE THREAD

**Issue by Mhs-220** [flavors/django-graphql-jwt#46]
Hey! thanks for your great work
how can i override authenticate function for login, to the way that user can login with both username or email as username?

**Comment by mongkok** [comment]
Hi @Mhs-220 and thanks :)

You should write a custom authentication backend:
https://docs.djangoproject.com/es/2.1/topics/auth/customizing/

If `get_user_model().USERNAME_FIELD == 'username'` then:

```py
from django.contrib.auth import get_user_model


class EmailBackend:

    def authenticate(self, request, username=None, password=None, **kwargs):
        if username is not None:
            UserModel = get_user_model()

            try:
                user = UserModel.objects.get(email__iexact=username)
            except UserModel.DoesNotExist:
                """Not found, try another backend"""
            else:
                if user.check_password(password):
                    return user
        return None
```

And add the backend to your `AUTHENTICATION_BACKENDS`:
```py
AUTHENTICATION_BACKENDS = [
    'graphql_jwt.backends.JSONWebTokenBackend',  # Authorization HTTP header
    'django.contrib.auth.backends.ModelBackend',  # UserModel.get(username=...)
    'mysite.mybackends.EmailBackend',  # UserModel.get(email__iexact=...)
]
```

**Comment by Mhs-220** [comment]
Thanks a lot! :) wish you bests ;)

**Comment by Cimmanuel** [comment]
@mongkok I did this already but for some weird reasons unknown to me, I am getting `"Please enter valid credentials"`. I know the credentials are correct, so it's not actually an issue the credentials

**Comment by cristiangrojas** [comment]
I've been looking for this solution for a while.

Thanks a lot for sharing.
