### ISSUE TITLE
token_auth set session cookie ?

### ISSUE THREAD

**Issue by tguillemot** [flavors/django-graphql-jwt#5]
Hi and thanks for your amazing work.

I had a look to your code and I don't understand why you need to use the [django.contrib.auth.login inside the token_auth](https://github.com/flavors/django-graphql-jwt/blob/master/graphql_jwt/decorators.py#L31). 

As explained by the django documentation, [login() saves the user’s ID in the session, using Django’s session framework](https://docs.djangoproject.com/en/2.0/topics/auth/default/#how-to-log-a-user-in) and I don't see why you need to store a cookie to save session information if you have a JWT token.

For me, the only case where such a thing can be useful is for the Server Side Rendering but the cookie needs to store the token instead of a session id.

Can you give me your point of view ?

Thanks in advance for your answer.

**Comment by mongkok** [comment]
Thanks @tguillemot, that's a good question.

The reason to include the login is to send the `user_logged_in` signal and update the `last_login` user field.

I totally agree with you, `ObtainJSONWebToken` should not save the user session, `login()` must disappear and may be replaced by the signal.

```python
from django.contrib.auth.signals import user_logged_in

user_logged_in.send(sender=user.__class__, request=info.context, user=user)
```

What do you think about sending this signal?

**Comment by tguillemot** [comment]
I had a look on how Django Rest Framework JWT solves that. 
It seems that they prefer not updating `last_login` [as explained on that issue](https://github.com/GetBlimp/django-rest-framework-jwt/issues/235#issuecomment-212284538).
As they said, by generating a JWT you fetch the user but do not update it.
I agree with that.

Do you have a case where `last_login` is useful for JWT ?

**Comment by mongkok** [comment]
In my opinion, `ObtainJSONWebToken` is a login process, the user sends his credentials and authenticates.

Perhaps it would be advisable to update it using the "Customizing" option and that each developer decides.

**Comment by tguillemot** [comment]
> In my opinion, ObtainJSONWebToken is a login process, the user sends his credentials and authenticates.

We can see things like that indeed. 

> Perhaps it would be advisable to update it using the "Customizing" option and that each developer decides.

I do not have a strong feeling on that. 
For me, it is not big deal if `last_login` is updated or not.
So, you can update `last_login` by default and if someone has a big problem with that one day he will open an issue anyway :smile:.

Thanks for your answers and discussions !!!

**Comment by mongkok** [comment]
Thanks, it was a pleasure talking to you :)

**Comment by kukirokuk** [comment]
last_login field is used as salt for generation tokens for links when email changes and password resets
