### ISSUE TITLE
Raise custom exception with decorators

### ISSUE THREAD

**Issue by kendallroth** [flavors/django-graphql-jwt#51]
It would be nice if the decorators would support raising a custom exception (see line in decorators). I would like to implement a `@verification_required` annotation that would extend the `@user_passes_test` function to include checking the custom verification field on the `User` model. However, it currently raises the permission error, rather than my own error for verification.

https://github.com/flavors/django-graphql-jwt/blob/master/graphql_jwt/decorators.py#L40

**Comment by mongkok** [comment]
Hi @kendallroth !,
I am sorry for the long long delay to response.

`@user_passes_test` decorator checks user permissions and raises a specific `PermissionDenied` exception just like Django framework.
https://docs.djangoproject.com/en/2.1/topics/auth/default/#django.contrib.auth.decorators.user_passes_test

You can use the `@context` decorator and raise your own exception.

**Comment by kendallroth** [comment]
Ah interesting, thanks for pointing that out! However, we actually wound up writing our own decorator for requiring login as we needed a similar decorator for requiring a verified account. Hopefully this issue is useful for someone else though! Thanks!
