### ISSUE TITLE
Return User with ObtainJSONWebToken and token_auth decorator

### ISSUE THREAD

**Issue by nwaxiomatic** [flavors/django-graphql-jwt#53]
currently the ObtainJSONWebToken mutation, specifically the @token_auth decorator, doesnt return the user with the token so you have to send two requests to get the user data after logging in. 

Because token_auth is written as a decorator (an area I'm not super comfortable with) it makes it difficult to extend this mutation to get the user data, so you currently have to rewrite the entire decorator just to add ```payload.user = user``` in the `on_resolve` method inside it.

**Comment by mongkok** [comment]
Hi @nwaxiomatic !,
you can add any field in the payload, see the documentation:
https://django-graphql-jwt.domake.io/en/latest/customizing.html
https://django-graphql-jwt.domake.io/en/latest/relay.html#customizing

**Comment by nwaxiomatic** [comment]
amazing thanks!
