### ISSUE TITLE
How to get user identity?

### ISSUE THREAD

**Issue by keyeMyria** [flavors/django-graphql-jwt#56]
How  to get user identity? just like [flask-jwt-extended](https://github.com/vimalloc/flask-jwt-extended) method get_jwt_identity

**Comment by mongkok** [comment]
Hi @keyeMyria,
can you provide more information on what the function `get_jwt_identity` consists of?,
It's used to encode the token or to obtain a user the given a token?

**Comment by keyeMyria** [comment]
The method [get_jwt_identity](https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/utils.py) just get the identity of user id

**Comment by roxel** [comment]
I'm not sure if this is what you asking but when you use Django Graphene resolve function you just need to access `info.context.user`? And there is also `get_payload` method in `utils`.

**Comment by mongkok** [comment]
Hi @keyeMyria, 
-[JWT_PAYLOAD_HANDLER](https://django-graphql-jwt.domake.io/en/stable/settings.html#jwt-payload-handler) setting variable decodes a JWT token and generates the token payload.
-[JWT_PAYLOAD_GET_USERNAME_HANDLER](https://django-graphql-jwt.domake.io/en/stable/settings.html#jwt-payload-get-username-handler) setting variable obtains the user-ID from the decoded payload.

I think the `get_jwt_identity` function looks like `JWT_PAYLOAD_GET_USERNAME_HANDLER`.

**Comment by mongkok** [comment]
I close the issue, if you have any questions please let me know.
