### ISSUE TITLE
Any idea how a flask users use graphql-jwt ?

### ISSUE THREAD

**Issue by kavink** [flavors/django-graphql-jwt#6]
Wondering if there are any similar projects for Flask users ? I would like my flask graphene-graphql app to have auth, ideally at per resource /model level or similar.

**Comment by mongkok** [comment]
Hi @kavink,

I have not seen similar projects for Flask and Graphene but there is a Flask library that could be a perfect toolkit to make it yourself.
https://github.com/vimalloc/flask-jwt-extended

flask-jwt-extended has functions to develop all mutations included in Django-graphql-jwt.
- `tokenAuth(username, password)`: [create_access_token()](http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.create_access_token)
- `verifyToken(token)`: [get_jwt_identity()](http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.get_jwt_identity)
- `refreshToken(token)`: [create_refresh_token()](http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.create_refresh_token)

and you could use the `@jwt_required` decorator to limit access to data.

```python
import graphene
import graphene_sqlalchemy
from flask_jwt_extended import current_user, jwt_required


class UserType(graphene_sqlalchemy.SQLAlchemyObjectType):

    class Meta:
        model = UserModel


class Query(graphene.ObjectType):
    viewer = graphene.Field(UserType)
    users = graphene.List(UserType)

    @jwt_required
    def resolve_viewer(self, info, **kwargs):
        return current_user

    @jwt_required
    # TODO: @superuser_required
    def resolve_users(self, info, **kwargs):
        return info.context['session'].query(UserModel).all()


class UpdateUser(graphene.Mutation):
    user = graphene.Field(UserType)

    class Arguments:
        email = graphene.String()

    @classmethod
    @jwt_required
    def mutate(cls, root, info, email):
        # TODO: update current_user
        return cls(user=current_user)
```

**Comment by gj1118** [comment]
@kavink - were you able to get it working with Flask - can you please provide me with an example code or point me to the correct direction , please ?

thank you

**Comment by hardntrash** [comment]
thx for answer. I tryed to use [Flask-GraphQL-Auth](https://flask-graphql-auth.readthedocs.io/en/latest/basic_usage.html), but your variant is best way.

> Hi @kavink,
> 
> I have not seen similar projects for Flask and Graphene but there is a Flask library that could be a perfect toolkit to make it yourself.
> https://github.com/vimalloc/flask-jwt-extended
> 
> flask-jwt-extended has functions to develop all mutations included in Django-graphql-jwt.
> 
>     * `tokenAuth(username, password)`: [create_access_token()](http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.create_access_token)
> 
>     * `verifyToken(token)`: [get_jwt_identity()](http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.get_jwt_identity)
> 
>     * `refreshToken(token)`: [create_refresh_token()](http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.create_refresh_token)
> 
> 
> and you could use the `@jwt_required` decorator to limit access to data.
> 
> ```python
> import graphene
> import graphene_sqlalchemy
> from flask_jwt_extended import current_user, jwt_required
> 
> 
> class UserType(graphene_sqlalchemy.SQLAlchemyObjectType):
> 
>     class Meta:
>         model = UserModel
> 
> 
> class Query(graphene.ObjectType):
>     viewer = graphene.Field(UserType)
>     users = graphene.List(UserType)
> 
>     @jwt_required
>     def resolve_viewer(self, info, **kwargs):
>         return current_user
> 
>     @jwt_required
>     # TODO: @superuser_required
>     def resolve_users(self, info, **kwargs):
>         return info.context['session'].query(UserModel).all()
> 
> 
> class UpdateUser(graphene.Mutation):
>     user = graphene.Field(UserType)
> 
>     class Arguments:
>         email = graphene.String()
> 
>     @classmethod
>     @jwt_required
>     def mutate(cls, root, info, email):
>         # TODO: update current_user
>         return cls(user=current_user)
> ```

**Comment by isakal** [comment]
This works beautifully, appreciate it

**Comment by danielkolesnik** [comment]
```python
class AuthMiddleware(object):
    def resolve(self, next, root, info, **kwargs):
        # This will only be called once for a request
        if root is None:
            # verify jwt if requested resource is not public
            if info.field_name not in ['tokenAuth', 'verifyToken']:
                verify_jwt_in_request()

                return next(root, info, **kwargs)

        return next(root, info, **kwargs)
```
