### ISSUE TITLE
Blacklist revoked tokens

### ISSUE THREAD

**Issue by Speedy1991** [flavors/django-graphql-jwt#60]
Currently there is only one way to logout the user: Remove the jwt on client side and therefore a logout-now is not possible atm.

Storing the refresh token in the token will solve this problem, e.g:

```
{
  "username": "user123",
  "exp": 1544626946,
  "origIat": 1544626646,
  "refresh_token": "2ffee69532059e3569cf69f47d611e670b8fc0b5"
}
```

When a token gets revoked we add the token to the django cache:
`cache.set(refresh_token.token, refresh_token.created + JWT_REFRESH_EXPIRATION_DELTA)`

In the authentication backend we just check if the token is in the cache:

```
def authenticate(self, request=None, **kwargs):
        if request is None:
            return None

        token = get_credentials(request, **kwargs)

        if token is not None:
            if cache.get(token["refresh_token"]):
                return None
            return get_user_by_token(token, request)

        return None
```

What do you think about this?
We also need to build the blacklist cache on startup - a simple manage.py command should do this job

**Comment by mongkok** [comment]
Hi @Speedy1991,
Why not revoke the refresh token when the user logs out?
```graphql
mutation RevokeToken($refreshToken: String!) {
  revokeToken(refreshToken: $refreshToken) {
    revoked
  }
}
```

**Comment by Speedy1991** [comment]
This will only prevent users from using the refresh token to obtain a new token

The problem is mainly with longer running tokens.
They will be still valid to login while the refresh token is revoked. In most cases it's enough to just delete the jwt from the client, but think about compromised/stolen tokens. There will be no way to prevent those from using the jwt

**Comment by mongkok** [comment]
Hi @Speedy1991 and sorry for the delay in my response.

In my opinion, it's not a good idea to include extra data that are not specified in the [RFC](https://tools.ietf.org/html/rfc7519).

On the other hand, the invalidation of a JWT token is a common problem independent of the refresh strategy.

*django-rest-framework-jwt* has some tickets related to this topic:
https://github.com/GetBlimp/django-rest-framework-jwt/issues/385

**Comment by mongkok** [comment]
I close the issue, if you have any questions please let me know.
