### ISSUE TITLE
JSON Encoder

### ISSUE THREAD

**Issue by mfdeux** [flavors/django-graphql-jwt#63]
pyJWT exposes a JSON encoder argument when encoding the payload, I suggest this is made a setting without having to make an entirely new jwt_encode function.  For example, my username field is a phone number which wasn't serializable into JSON.

```python
def jwt_encode(payload, context=None):
    return jwt.encode(
        payload,
        jwt_settings.JWT_SECRET_KEY,
        jwt_settings.JWT_ALGORITHM,
        json_encoder=jwt_settings.JWT_JSON_ENCODER
    ).decode('utf-8')
```

**Comment by mongkok** [comment]
Hi @mfdeux,
I'm not sure if we should create a new variable for the *json_encoder*,
why not use the setting variable [JWT_ENCODE_HANDLER](https://django-graphql-jwt.domake.io/en/stable/settings.html#jwt-encode-handler)?

```py
from graphql_jwt.utils import jwt_encode

def custom_jwt_encode(payload, context=None):
    # payload['phone'] = ...
    return jwt_encode(payload, context)
```

*settings.py*
```py
GRAPHQL_JWT = {
    'JWT_ENCODE_HANDLER': '...custom_jwt_encode',
}

**Comment by Musbell** [comment]
@mongkok I tried your example bur i am getting this error: ```{
  "errors": [
    {
      "message": "not enough values to unpack (expected 2, got 1)",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "tokenAuth"
      ]
    }
  ],
  "data": {
    "tokenAuth": null
  }
}```

**Comment by Musbell** [comment]
Now i get it. `custom_jwt_encode` wasn't referenced properly

**Comment by mongkok** [comment]
Hi @Musbell and sorry for the delay in my response.

I'm not sure, check the module to import `custom_jwt_encode`:

`/utils.py`
```py
from graphql_jwt.utils import jwt_encode

def custom_jwt_encode(payload, context=None):
    # payload['phone'] = ...
    return jwt_encode(payload, context)
```

`/settings.py`
```py
GRAPHQL_JWT = { 
    'JWT_ENCODE_HANDLER': 'utils.custom_jwt_encode',
}
```

I close the issue, if you have any questions please let me know.
