### ISSUE TITLE
Is it possible to use with Django Defender?

### ISSUE THREAD

**Issue by kennandavison** [flavors/django-graphql-jwt#64]
Has anyone tried using django-defender or some login throttle library? 

Seems like one would need to modify decorators.py's token_auth to use custom logic like the example here: https://github.com/kencochrane/django-defender#adapting-to-other-authentication-method

**Comment by kennandavison** [comment]
Figured it out: https://github.com/flavors/django-graphql-jwt/pull/65

**Comment by mongkok** [comment]
Hi @kennandavison and sorry for the delay in my response.

In my opinion `django-defender` and `redis` can not be a requirement for this package, it should be optional and configurable.

I'm sorry, but I have to refuse the pull request https://github.com/flavors/django-graphql-jwt/pull/65.

**Comment by mongkok** [comment]
I close the issue, if you have any questions please let me know.
