### ISSUE TITLE
'ResolveInfo' object has no attribute 'path' in middleware

### ISSUE THREAD

**Issue by darktal91** [flavors/django-graphql-jwt#69]
Whenever the server receives a request with the HTTP header `'Authorization':'JWT <token>'` the response contains the error 
> 'ResolveInfo' object has no attribute 'path'

Playing around with the debugger I noticed that the exception is raised from the 'resolve' method in the 'JSONWebTokenMiddleware' class of the middleware.py file.

The exception is caused by this piece of code:
`field = getattr(
                info.schema,
                'get_{}_type'.format(info.operation.operation),
            )().fields.get(info.path[0])`
The exception says that 'info' does not have the attribute 'path'. 
Playing with the debugger I noticed that the 'path' attribute exists inside the 'context' object. So I tried to change the code from `info.path[0]` to `info.context.path[0]` and everything started working correctly.

Since I'm fairly new to both Django and GraphQL I ask you: am I missing something here? Did I do something wrong in my code (i.e. url patterns, GraphQL types definitions, etc.) or in my settings/configurations that caused the info object to not have the expected structure? Is there something I can do to fix the problem? Obviously manually changing the library code is not the answer.

Thanks.

**Comment by mongkok** [comment]
Hi @darktal91 ,
What version of [graphql-core](https://github.com/graphql-python/graphql-core) do you have installed?

```sh
pip freeze|grep graphql-core
```

**Comment by Benjaminryejones** [comment]
Hey @mongkok,

Not trying to hijack, but just ran into the same issue after starting to use graphql_jwt.middleware.JSONWebTokenMiddleware

graphql-core version is 2.0

Other configs (in case helpful):
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
AUTHENTICATION_BACKENDS = [
    'graphql_jwt.backends.JSONWebTokenBackend',
    'django.contrib.auth.backends.ModelBackend',
]
GRAPHQL_JWT = {
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_EXPIRATION_DELTA': timedelta(minutes=5),
    'JWT_REFRESH_EXPIRATION_DELTA': timedelta(days=30),
}

Happy to answer any questions!

**Comment by Benjaminryejones** [comment]
Update:
Issue was resolved by upgrading to graphql-core 2.1

**Comment by mongkok** [comment]
Thanks @Benjaminryejones !,
I've added *graphql-core* to the `install_requires`.
