### ISSUE TITLE
Python2 support

### ISSUE THREAD

**Issue by maledorak** [flavors/django-graphql-jwt#7]
Hi, there is any chances for python2 support?

Python2.7 and Django 1.11 has support until April 2020.
I'm sure that many large django 1.11 projects will stay with python2.7 for some time from now (including this used in my company).

I can create PR for this issue.

**Comment by mongkok** [comment]
Thanks @maledorak,

you are quite right, there should be support for Python 2.7.
I have more libraries with this issue, I wouldn't mind, if you agree, to do the changes myself.

**Comment by mongkok** [comment]
@maledorak done, you can upgrade to version 0.1.7.

**Comment by maledorak** [comment]
@mongkok you are like a flash :)
Thank you

**Comment by mongkok** [comment]
thanks for suggesting changes :)
