### ISSUE TITLE
Migrations not up 2 date

### ISSUE THREAD

**Issue by onceatime** [flavors/django-graphql-jwt#70]
when we run makemigrations a new migration in /graphql_jwt/refresh_token/migrations/0002_auto_20190123_1648.py gets created with the following content:

```
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refresh_token', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refreshtoken',
            options={'verbose_name': 'refresh token', 'verbose_name_plural': 'refresh tokens'},
        ),
    ]
```

in ci we check if any uncreated migrations exist. if yes it stops the deployment. This happens because.

in https://github.com/flavors/django-graphql-jwt/blob/v0.2.0/graphql_jwt/refresh_token/migrations/0001_initial.py

```
'verbose_name': 'Refresh token', # uppercase, line 27
'verbose_name_plural': 'Refresh tokens', # uppercase, line 28
```

but in https://github.com/flavors/django-graphql-jwt/blob/v0.2.0/graphql_jwt/refresh_token/models.py

```
verbose_name = _('refresh token')  # lowercase, line 35
verbose_name_plural = _('refresh tokens') # lowercase, line 36
```

**Comment by mongkok** [comment]
Hi @onceatime !,
I prefer to use lowercase,
could you update the migration to lowercase instead of the model class?

Thanks.

**Comment by mongkok** [comment]
@onceatime thanks!
