### ISSUE TITLE
Don't generate a refreshToken if it was not requested

### ISSUE THREAD

**Issue by ktosiek** [flavors/django-graphql-jwt#72]
Currently refresh tokens are created on each login. It would be great to only generate them when the refreshToken field was requested.

Would that make sense as a PR?

**Comment by mongkok** [comment]
Hi @ktosiek!
I created a pull request #77 to fix this.
I'll release a new version on PyPI as soon as this PR is merged.

**Comment by ktosiek** [comment]
Thank you!
I'll have to remember that usage of `lazy`, it's really clever.
