### ISSUE TITLE
What about verifyToken when using long running refresh tokens?

### ISSUE THREAD

**Issue by googol7** [flavors/django-graphql-jwt#74]
Some clarification regarding verifyToken when using long running refresh tokens would be nice here:

https://django-graphql-jwt.domake.io/en/stable/refresh_token.html?highlight=verifyToken#long-running-refresh-tokens

**Comment by mongkok** [comment]
Hi @googol7 !
`verifyToken` does not depend on the refreshing method and is documented here:
https://django-graphql-jwt.domake.io/en/latest/quickstart.html

What is your proposal?

**Comment by mongkok** [comment]
I close the issue, if you have any questions please let me know.
