### ISSUE TITLE
Adding more authentication fields

### ISSUE THREAD

**Issue by Glyphack** [flavors/django-graphql-jwt#84]
Hi,
These days authenticating with email or mobile number are very common, I also use them. one solution to add these methods is to create custom authentication methods which gets username and search the username in other fields. certainly it's not a clean solution, a better approach would be adding more fields to mutation or letting users add they're own fields and they're own authenticators which takes those fields.

**Comment by mongkok** [comment]
Hi @Glyphack ,
I'm sorry for the delay in my response.

I have created a [PR #87](https://github.com/flavors/django-graphql-jwt/pull/87) including an example to authenticate users using multiple fields.

If you have any questions, please let me know.

**Comment by JSeam2** [comment]
Hi @mongkok, after providing the custom_get_user_by_natural_key will the additional fields added reflect in the `ObtainJSONWebToken` function? I have pulled the code from master and it does not seem to be the case. Is there anything that I am missing on?

**Comment by JSeam2** [comment]
Hi @mongkok, after providing the custom_get_user_by_natural_key will the additional fields added reflect in the `ObtainJSONWebToken` function? I have pulled the code from master and it does not seem to be the case. Is there anything that I am missing on?

**Comment by mongkok** [comment]
Hi @JSeam2 and I'm sorry for the delay in my response.

You can use a single input field and use that value to look up the user on different fields.

e.g.
`USERNAME_FIELD = 'email'`

Input field names:
- email (`USERNAME_FIELD`), for username and email.
- password

```py
from django.contrib.auth import get_user_model
from django.db.models import Q


def custom_get_user_by_natural_key(username):
    User = get_user_model()
    try:
        return User.objects.get(Q(username=username) | Q(email=username))
    except User.DoesNotExist:
        return None


GRAPHQL_JWT = {
    'JWT_GET_USER_BY_NATURAL_KEY_HANDLER': custom_get_user_by_natural_key
}
```

I close the issue, if you have any questions please let me know.
