### ISSUE TITLE
social auth / Oauth - insights?

### ISSUE THREAD

**Issue by gotexis** [flavors/django-graphql-jwt#85]
any insights?

**Comment by mongkok** [comment]
Hi @gotexis ,
This package is relying on [Python Social Auth](https://github.com/python-social-auth):
https://github.com/flavors/django-graphql-social-auth

If you have any questions, please let me know.

**Comment by gotexis** [comment]
@mongkok 

Thanks!

I was struggling to get anything right until I saw the project you posted. Let me research into it and will update on any progress.

**Comment by mongkok** [comment]
Hi @gotexis ,
I would just add that you can use cookie authentication instead of storing the token:
https://django-graphql-jwt.domake.io/en/stable/authentication.html#per-cookie
