### ISSUE TITLE
"You do not have permission to perform this action" error on production server

### ISSUE THREAD

**Issue by Kendysond** [flavors/django-graphql-jwt#88]
Hi, 

I recently deployed my application on a live server, and for some weird reason all my requests to mutations that are wrapped in the `@login_required` decorator keep returning the error "You do not have permission to perform this action". 

My settings are a replica of what's on the documentation. 

For more context: I use a custom login mutation where I use the ` token = get_token(user)` shortcut to generate the JWT token. 

All of this works on my localhost, however it's not working in production. 

I did a little digging and it seems the code is not respecting the JWT passed in the header Authorization. I know this because, if I use the `graphql_jwt.ObtainJSONWebToken.Field()` mutation to login, it seems to set a cookie that then logs the user and returns the correct responses for all those endpoints wrapped in  `@login_required`

Anybody experienced this before? I'm fine with it setting a cookie if that's the only way, I'd just like to know how to authenticate users with a custom function and also have the token returned in my custom sign up and login mutation. 

Any help would be really appreciated. 

Thank you.

**Comment by Kendysond** [comment]
Figured it out. My server is AWS Elastic Beanstack, and for some reason `WSGIPassAuthorization` is turned off, so I had to enable "WSGIPassAuthorization On" to get it to work. 

https://stackoverflow.com/a/25862505

**Comment by YasinYA** [comment]
I am experiencing this in development mode. How did you solve it in ur dev env. @Kendysond

**Comment by valentindjangone** [comment]
@YasinYA Did you find a solution for that problem ?
