### ISSUE TITLE
not authenticating against django python ldap3

### ISSUE THREAD

**Issue by arif-hanif** [flavors/django-graphql-jwt#89]
https://github.com/flavors/django-graphql-jwt/blob/master/graphql_jwt/decorators.py#L85

`user = authenticate(
            request=info.context,
            username=username,
            password=password,
            skip_jwt_backend=True)`

what is the purpose of the skip_jwt_backend variable?

This is causing an issue with the django ldap 3 backend

**Comment by mongkok** [comment]
Hi @arif-hanif and I'm sorry for the delay in my response.

When a user authenticates, the JWT token should not be taken into account, that is the purpose of the `skip_jwt_backend` argument.

*django ldap 3* uses the `authenticate()` arguments to look up the user, you can configure this behavior with the configuration variable `LDAP_AUTH_FORMAT_SEARCH_FILTERS` 

Anyway, I've remove this argument https://github.com/flavors/django-graphql-jwt/commit/6bf91bfb1e8a6868746b7f313f3d1aa7b4b8a062.

I close the issue, if you have any questions please let me know.
