### ISSUE TITLE
Deprecated middleware classes support

### ISSUE THREAD

**Issue by maledorak** [flavors/django-graphql-jwt#9]
Hi again @mongkok

I have a proposition about old Django MIDDLEWARE_CLASSES support.
Because Django will be deprecated this old middleware style support in 2.0 version (check in link below)
[Django 2.0 deprecation timeline](https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-2-0)

And still, many Django apps are used only Django 1.11
So when we want to use django-graphql-jwt, we must change MIDDLEWARE_CLASSES to MIDDLEWARE, but then few of other older apps, which still don't support Django 2.0 don't work.

I found a simple solution to this stalemate in [django-cors-headers](https://github.com/ottoyiu/django-cors-headers) app.
check files:
https://github.com/ottoyiu/django-cors-headers/blob/master/corsheaders/middleware.py
and especially
https://github.com/ottoyiu/django-cors-headers/blob/master/corsheaders/compat.py

What do you think about adding this support?
Thank you for your great work :)

**Comment by mongkok** [comment]
Hi again @maledorak and thanks for the suggestion, I also think it's a good idea to support the old middleware for Django 1.11.

**Comment by mongkok** [comment]
done!
```sh
pip install django-graphql-jwt==0.1.8
```

**Comment by maledorak** [comment]
@mongkok Thank you :)
