### ISSUE TITLE
How to use with Django Rest Framework?

### ISSUE THREAD

**Issue by GiancarlosIO** [flavors/django-graphql-jwt#90]
Hi

Is there a way to authenticate an user in DRF using the same jwt of django-graphql-jwt?
I have a custom Django class view and I want to access to the user if the `Authorization: jwt <token>` is in the request headers.
Can I reuse the same middlewares/mixins to authenticate the user in normal Django views?

Thanks.

**Comment by mongkok** [comment]
Hi @GiancarlosIO and I'm sorry for the delay in my response.

- Graphene:  Add `graphql_jwt.middleware.JSONWebTokenMiddleware` to GRAPHENE settings.
- DRF: you can create an authentication class that inherits from `rest_framework.authentication. BaseAuthentication` and add it to `DEFAULT_AUTHENTICATION_CLASSES `, I will add this class to this package soon.
- Django Views: you can use `graphql_jwt.middleware.DjangoMiddleware` source, but exclude Graphene/DRF paths to avoid double authentication.

**Comment by GiancarlosIO** [comment]
@mongkok Hey no problem, I did the exactly the same that you say 2h after create this issue.
Thank you!

**Comment by mongkok** [comment]
This package will not support DRF.
I close the issue.

**Comment by demux** [comment]
Maybe this will be useful to someone:

```python
from graphql_jwt.exceptions import JSONWebTokenError
from graphql_jwt.utils import get_payload, get_user_by_payload
from rest_framework.authentication import BaseAuthentication, get_authorization_header
from rest_framework import exceptions


class TokenAuthentication(BaseAuthentication):
    keyword = 'JWT'

    def authenticate(self, request):
        auth = get_authorization_header(request).split()

        if not auth or auth[0].lower() != self.keyword.lower().encode():
            return None

        if len(auth) == 1:
            msg = 'Invalid token header. No credentials provided.'
            raise exceptions.AuthenticationFailed(msg)
        elif len(auth) > 2:
            msg = 'Invalid token header. Token string should not contain spaces.'
            raise exceptions.AuthenticationFailed(msg)

        try:
            token = auth[1].decode()
        except UnicodeError:
            msg = 'Invalid token header. Token string should not contain invalid characters.'
            raise exceptions.AuthenticationFailed(msg)

        try:
            payload = get_payload(token)
            user = get_user_by_payload(payload)
        except JSONWebTokenError as e:
            raise exceptions.AuthenticationFailed(str(e))

        if user is None or not user.is_active:
            raise exceptions.AuthenticationFailed('User inactive or deleted.')

        return (user, None)

    def authenticate_header(self, request):
        return self.keyword
```
