### ISSUE TITLE
refreshToken Does Not Take Arguments

### ISSUE THREAD

**Issue by Benjaminryejones** [flavors/django-graphql-jwt#92]
Hello,

I see [in the code for the "Refresh" mutation type](https://github.com/flavors/django-graphql-jwt/blob/65a86a37500b50be58d6b2249570296e395af071/graphql_jwt/mutations.py) that the mutation [should take the arguments from the RefreshMixin](https://github.com/flavors/django-graphql-jwt/blob/65a86a37500b50be58d6b2249570296e395af071/graphql_jwt/mixins.py).

However, when I try to use either the default refresh tokens or 'JWT_LONG_RUNNING_REFRESH_TOKEN': True, I am unable to pass in a "token" argument:
![image](https://user-images.githubusercontent.com/10845447/56550123-9c387e00-6539-11e9-94e3-50d698aafa36.png)

I am using python 3.6, graphql-core 2.1, django 2.1.4, graphene-django 2.0.0, django-graphql-jwt 0.2.1

Thanks!

**Comment by Glyphack** [comment]
Hi,
according to docs if you set `JWT_LONG_RUNNING_REFRESH_TOKEN` to true you need to pass refreshToken to this mutation if it's False you should pass token.
Is there anything else?

**Comment by mongkok** [comment]
Hi @Benjaminryejones and I'm sorry for the delay in my response.

If you set `JWT_LONG_RUNNING_REFRESH_TOKEN` to `True` the `RefreshToken` mutation should accept a `refreshToken` argument.

What is your `GRAPHQL_JWT` settings?

```py
GRAPHQL_JWT = {
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LONG_RUNNING_REFRESH_TOKEN': True,
}
```

**Comment by mongkok** [comment]
I close the issue, if you have any questions please let me know.
