### ISSUE TITLE
Missing migration for refresh_tokens plural related_name

### ISSUE THREAD

**Issue by mobiware** [flavors/django-graphql-jwt#93]
The following commit changed the `related_name` of `RefreshToken.user` but the accompanying migration file is missing
https://github.com/flavors/django-graphql-jwt/commit/6f38e892d2820f99b5dd5374376970eae82abb00

So when using version `0.2.1` Django complains there are pending changes to the model

**Comment by mongkok** [comment]
Thanks @mobiware and I'm sorry for the delay in my response.

Fixed!
