### ISSUE TITLE
mutation for itegrating django login with jwt.

### ISSUE THREAD

**Issue by Glyphack** [flavors/django-graphql-jwt#94]
For some users, like me, having a login mutation that signs user in and giving them a refreshToken and authenticate with django, and a logout mutation that revokes user token and signs out user from website (and also if user used login without jwt server should generate refreshToken for them to sign-in them in app).
do you think this should be implemented in this package or there should be a guide for implementing this?

**Comment by mongkok** [comment]
Hi @Glyphack,
I'm sorry for the delay in my response.

If you mean to use the Django’s session framework, this should not be included in this package, see also https://github.com/flavors/django-graphql-jwt/issues/5.
Why need you save the user’s session when you are authenticating with JWT?

**Comment by Glyphack** [comment]
In my case not all the app is using jwt auth and part of it is using view, template from django itself. I want user to be logged in in both sides do you have better solution for this?

**Comment by mauricio-chavez** [comment]
@Glyphack you can do something like this in your project schema

```python
import graphql_jwt

class Mutation(graphene.ObjectType):
    """Mutation Object for project Schema"""
    token_auth = graphql_jwt.ObtainJSONWebToken.Field()
    verify_token = graphql_jwt.Verify.Field()
    refresh_token = graphql_jwt.Refresh.Field()
```

And then you can make those mutations. I suggest you to make also a mutation for signup, by the way.

Then, to use it in some mutations or queries, you can do something like this in queries:

```python
import graphene
from graphql_jwt.decorators import login_required

class Query(graphene.ObjectType):
    """Query Object for project Schema"""
    hello = graphene.String()

    @login_required
    def resolve_hello(self, info, **kwargs):
        return f'Hello, { info.context.user.first_name }'
```

And, you can do something like this in a mutation:

```python
import graphene
from graphql_jwt.decorators import login_required

class CreateItem(graphene.Mutation):
    """Mutation that creates an item"""
    hello = graphene.String()

    class Arguments:
        """Args that are allowed in mutation"""
        name = graphene.String(required=True)

    @login_required
    def mutate(self, info, name):
        """Says hello but in a mutation"""
        return f'Hello, { name }'
```

I hope you find it useful! 😄

**Comment by mongkok** [comment]
@Glyphack, 
I consider the best approach to implement a second mutation to [login()](https://docs.djangoproject.com/en/2.2/topics/auth/default/#django.contrib.auth.login).
This way you can call the 2 mutations with one single request.

I close the issue, if you have any questions please let me know.
