### ISSUE TITLE
JSONWebTokenError(_('Please, enter valid credentials')) is thrown for existing, but not activated user

### ISSUE THREAD

**Issue by TitanFighter** [flavors/django-graphql-jwt#96]
If someone faced the issue like below:
If user exists but not active (for example user just registered but has to confirm activation via email link) and if this user tries to login `django-graphql-jwt` returns the message `Please, enter valid credentials` ([source](https://github.com/flavors/django-graphql-jwt/blob/master/graphql_jwt/decorators.py#L87)).

**Reason of this issue:**
Before Django v1.10 "authenticate" from "django.contrib.auth" did not check "is_active". Since v1.10 it was changed.

**Solution:**
So, in order to let  "authenticate" from "django.contrib.auth" to continue ignoring "is_active", it is necessary to change `'django.contrib.auth.backends.ModelBackend'` to `'django.contrib.auth.backends.AllowAllUsersModelBackend'` in `AUTHENTICATION_BACKENDS` block of Django settings.

You can compare [v1.9](https://docs.djangoproject.com/en/1.9/ref/contrib/auth/#django.contrib.auth.models.User.is_active) `is_active` description and [v1.10](https://docs.djangoproject.com/en/1.10/ref/contrib/auth/#django.contrib.auth.models.User.is_active):

**v1.9:**

> is_active
> 
>     Boolean. Designates whether this user account should be considered active. We recommend that you set this flag to False instead of deleting accounts; that way, if your applications have any foreign keys to users, the foreign keys won’t break.
> 
>     This doesn’t necessarily control whether or not the user can log in. Authentication backends aren’t required to check for the is_active flag, and the default backends do not. If you want to reject a login based on is_active being False, it’s up to you to check that in your own login view or a custom authentication backend. However, the AuthenticationForm used by the login() view (which is the default) does perform this check, as do the permission-checking methods such as has_perm() and the authentication in the Django admin. All of those functions/methods will return False for inactive users.

**v1.10:**

> is_active
> 
>     Boolean. Designates whether this user account should be considered active. We recommend that you set this flag to False instead of deleting accounts; that way, if your applications have any foreign keys to users, the foreign keys won’t break.
> 
>     This doesn’t necessarily control whether or not the user can log in. Authentication backends aren’t required to check for the is_active flag but the default backend (ModelBackend) and the RemoteUserBackend do. You can use AllowAllUsersModelBackend or AllowAllUsersRemoteUserBackend if you want to allow inactive users to login. In this case, you’ll also want to customize the AuthenticationForm used by the login() view as it rejects inactive users. Be aware that the permission-checking methods such as has_perm() and the authentication in the Django admin all return False for inactive users.
>     Changed in Django 1.10:
> 
>     In older versions, ModelBackend and RemoteUserBackend allowed inactive users to authenticate.
>

**Comment by mostafaghadimi** [comment]
Would someone explain how this error resolved?

**Comment by spring1357** [comment]
I faced same issue and I need it to detect if failure in login is because of invalid credentials or user is not active. Is there any way to get proper error message and display to user? Right now if user is inactive or is active but used wrong username and password, same message is displayed to him.
