### ISSUE TITLE
Warning if inheriting from JSONWebTokenMiddleware

### ISSUE THREAD

**Issue by tetrohed** [flavors/django-graphql-jwt#97]
**ISSUE**
Following Warning in **JSONWebTokenMiddleware**, gets in the way of inheriting from JSONWebTokenMiddleware
`if JSONWebTokenMiddleware not in graphene_settings.MIDDLEWARE:
            warnings.warn(
                'Add'
                '\'graphql_jwt.middleware.JSONWebTokenMiddleware\' '
                'to your GRAPHENE[\'MIDDLEWARE\'] setting and remove it '
                'from your Django middleware classes.'
                'Please see the documentation for more information: '
                '<https://github.com/flavors/django-graphql-jwt#installation>',
                stacklevel=2)`

**EXPECTATION**
it should be possible to do 
`class CustomJsonWebTokenMiddleware(JSONWebTokenMiddleware):
    def __init__(self, get_response=None):
        super(CustomJsonWebTokenMiddleware, self).__init__(get_response)

    def resolve(self, next, root, info, **kwargs):
        return super(CustomJsonWebTokenMiddleware, self).resolve(next, root, info, **kwargs)`

**WHY**
One might need to add some APIs to white list, to circumvent the JWT middleware altogether. This is the case if an architecture decides to use a single endpoint for public and protected APIs

**Comment by mongkok** [comment]
Hi @tetrohed ,
You can add a list of classes to allow unrestricted access on them with the settings variable [JWT_ALLOW_ANY_CLASSES](https://django-graphql-jwt.domake.io/en/stable/settings.html#jwt-allow-any-classes).

On the other hand, you should be able to inherit from `JSONWebTokenMiddleware`, I will remove the warning for the next release.

**Comment by tetrohed** [comment]
cool thanks
