### ISSUE TITLE
How to log token-related activities

### ISSUE THREAD

**Issue by dsun-ge** [flavors/django-graphql-jwt#98]
Hi all,

How can I log user obtaining token and refreshing token activities? Like who logged in from what IP address?

Regards,
Dayong

**Comment by mongkok** [comment]
Hi @dsun-ge ,
You can use this signal:
https://django-graphql-jwt.domake.io/en/latest/signals.html#token-issued

I will create a new release soon.
I close the issue, if you have any questions please let me know.
